# This file is generated by scripts/generate_renames.jl from scripts/renames.jl.
# Do not edit it: edit the register and regenerate.
#
# One test per shim (docs/src/man/naming.md §17.3). This is the only file in the
# suite that calls the v0.4 names; everything else is on the v0.5 API.
#
# A forwarding shim warns before it forwards, so calling it with an argument the
# replacement cannot accept still proves that the shim exists, warns, and hands
# the call on. `Probe` is that argument.

using Test
using PETSc

struct DeprecationProbe end

# `@petsc_*_fn` read `PetscInt`/`PetscReal`/`PetscScalar` out of the calling module,
# so the expansion needs a module that has them.
module DeprecationMacroEnv
using PETSc
const PetscInt = Int64
const PetscReal = Float64
const PetscScalar = Float64
probe_simple(t, x, u, ctx) = nothing
probe_point(args...) = nothing
const Nf = 1
end

warns(f) = @test_logs (:warn, r"deprecated") match_mode = :any f()

# Call a shim in a way that reaches the warning but cannot go wrong afterwards.
function probe_shim(name::Symbol)
    f = getproperty(PETSc, name)
    warns() do
        try
            f(DeprecationProbe())
        catch
            # A MethodError from the replacement is the expected outcome: the
            # point of the call is that the warning was emitted on the way.
        end
    end
end

"""
Every shim in scripts/renames.jl, as `old => new`.
"""
const SHIMS = [
    :destroy => :destroy!,
    :getinfo => :info,
    :getcorners => :corners,
    :getcorners_dmda => :corners,
    :getghostcorners => :ghost_corners,
    :getghostcorners_dmda => :ghost_corners,
    :dm_local_to_global! => :local_to_global!,
    :dm_global_to_local! => :global_to_local!,
    :setuniformcoordinates_dmda! => :set_uniform_coordinates!,
    :coordinatesDMLocalVec => :local_coordinates,
    :getlocalcoordinatearray => :local_coordinate_array,
    :DMGlobalVec => :global_vec,
    :DMLocalVec => :local_vec,
    :getdimension => :ndims,
    :setfromoptions! => :set_from_options!,
    :getcorners_dmstag => :corners,
    :getghostcorners_dmstag => :ghost_corners,
    :local_indices_dmstag => :local_indices,
    :global_indices_dmstag => :global_indices,
    :setuniformcoordinates_stag! => :set_uniform_coordinates!,
    :DMStagDOF_Slot => :dof_slot,
    :reshapelocalarray => :reshape_local_array,
    :localinteriorlinearindex => :local_interior_linear_index,
    :dmda_star_fd_coloring => :star_fd_coloring,
    :isplexsimplex => :issimplex,
    :plexdistribute! => :distribute!,
    :petsc_setname! => :set_name!,
    :getds => :ds,
    :createds! => :create_ds!,
    :getlabel => :label,
    :dm_project_function! => :project_function!,
    :dm_project_field! => :project_field!,
    :dm_compute_l2diff => :l2diff,
    :dm_create_global_vec => :global_vec,
    :dm_create_local_vec => :local_vec,
    :dm_set_auxiliary_vec! => :set_auxiliary_vec!,
    :dm_coarsen_hook_add! => :add_coarsen_hook!,
    :dm_copy_disc! => :copy_disc!,
    :dm_get_coarse => :coarse_dm,
    :fe_copy_quadrature! => :copy_quadrature!,
    :mat_null_space_create => :mat_nullspace_create,
    :mat_set_null_space! => :set_nullspace!,
    :mat_null_space_destroy! => :destroy!,
    :vtk_save! => :save_vtk!,
    :vtk_save_fields! => :save_vtk!,
    :setfield! => :set_field!,
    :dmclone => :clone,
    :plex_set_snes_local_fem! => :set_snes_local_fem!,
    :snes_set_jacobian_null_space! => :set_jacobian_nullspace!,
    :fe_compose_constant_null_space! => :compose_constant_nullspace!,
    :getDM => :dm,
    :setDM! => :set_dm!,
    :get_solution => :solution,
    :gettype => :type_name,
    :type => :type_name,
    :setcomputeoperators! => :set_compute_operators!,
    :setcomputerhs! => :set_compute_rhs!,
    :setfunction! => :set_function!,
    :setjacobian! => :set_snes_jacobian!,
    :setconvergencetest! => :set_convergence_test!,
    :VecSeq => :PetscVec,
    :MatSeqAIJ => :PetscMat,
    :MatSeqDense => :PetscMat,
    :MatCreateSeqAIJ => :PetscMat,
    :MatSeqAIJWithArrays => :PetscMat,
    :MatAIJ => :PetscMat,
    :unsafe_localarray => :unsafe_local_array,
    :wrap_localarray => :wrap_local_array,
    :acquire_petsc_local_array => :acquire_local_array,
    :release_petsc_local_array => :release_local_array,
    :get_petsc_arrays => :local_arrays,
    :restore_petsc_arrays => :restore_local_arrays!,
    :withlocalarray! => :with_local_array!,
    :ghostupdate! => :ghost_update!,
    :ghostupdatebegin! => :ghost_update_begin!,
    :ghostupdateend! => :ghost_update_end!,
    :ownershiprange => :ownership_range,
    :setvalues! => :set_values!,
    :addindex! => :add_index!,
    :determine_memtype => :memtype,
    :Options => :PetscOptions,
    :set_petsclib => :PetscLibType,
    :initialized => :isinitialized,
    :finalized => :isfinalized,
    :check_petsc_wrappers_version => :check_wrappers_version,
    :getcomm => :comm,
    :typedget => :parse_option,
    :audit_petsc_file => :audit_file,
]

@testset "deprecations" begin
    @testset "every shim exists, warns and forwards" begin
        for (old, new) in SHIMS
            @test isdefined(PETSc, old)
            @test isdefined(PETSc, new) || isdefined(Base, new)
            probe_shim(old)
        end
    end

    @testset "renamed types are aliases" begin
        @test PETSc.Fn_KSPComputeRHS === PETSc.KSPComputeRHSFn
        @test PETSc.Fn_KSPComputeOperators === PETSc.KSPComputeOperatorsFn
        @test PETSc.Fn_SNESSetFunction === PETSc.SNESSetFunctionFn
        @test PETSc.Fn_SNESSetJacobian === PETSc.SNESSetJacobianFn
        @test PETSc.Fn_SNESSetConvergenceTest === PETSc.SNESSetConvergenceTestFn
        @test PETSc.AbstractPETScMemBackend === PETSc.AbstractPetscMemBackend
    end

    @testset "renamed macros warn and forward" begin
        warns() do
            macroexpand(DeprecationMacroEnv, :(PETSc.@petsc_residual_fn(probe_point, Nf)))
        end
        warns() do
            macroexpand(DeprecationMacroEnv, :(PETSc.@petsc_jacobian_fn(probe_point, Nf)))
        end
        warns() do
            macroexpand(DeprecationMacroEnv, :(PETSc.@petsc_bd_fn(probe_point, Nf)))
        end
        warns() do
            macroexpand(DeprecationMacroEnv, :(PETSc.@petsc_simple_fn(probe_simple)))
        end
    end

    @testset "a shim really does forward" begin
        petsclib = PETSc.petsclibs[1]
        PETSc.initialize(petsclib)
        v = PETSc.PetscVec(petsclib, 5)
        # `destroy` is the busiest shim in the rename; check it actually destroys.
        warns() do
            PETSc.destroy(v)
        end
        @test v.ptr == C_NULL
        @test (warns() do
            PETSc.initialized(petsclib)
        end) == PETSc.isinitialized(petsclib)
    end
end
