# Support files: enums, string enums, typedefs, opaque type declarations, version, prologue

function write_enums(io::IO, api::API, exclude::Set{String})
    for name in sort!(collect(keys(api.enums)))
        name in exclude && continue
        println(io, "@enum $name begin")
        for (i, v) in enumerate(api.enums[name])
            occursin("DEPRECATED", v) && continue      # deprecated aliases duplicate a value
            if occursin("=", v)
                println(io, "    $v")
            else
                println(io, "    $v = $(i-1)")
            end
        end
        println(io, "end \n")
    end
end

function write_senums(io::IO, api::API, r::Rules)
    println(io, "# not quite sure yet how to deal with this")
    for name in sort!(collect(keys(api.senums)))
        println(io, "$name=$(get(r.senum_overrides, name, "Ptr{Cchar}"))")
    end
end

function write_typedefs(io::IO, api::API, r::Rules, exclude::Set{String}, hand_blocks::Vector{String})
    names = sort!(filter(n -> !(n in exclude), collect(keys(api.typedefs))))
    values = Dict(n => map_type(r, api.typedefs[n]) for n in names)
    # dependency order: a typedef whose value names another pending typedef waits for it
    pending = copy(names)
    while !isempty(pending)
        progressed = false
        for n in copy(pending)
            deps = [m for m in pending if m != n && occursin(Regex("\\b" * m * "\\b"), values[n])]
            isempty(deps) || continue
            println(io, "const $n = $(values[n])")
            filter!(!=(n), pending)
            progressed = true
        end
        progressed || error("typedef cycle among $(pending)")
    end
    for b in hand_blocks
        println(io, b)
    end
end

"""Names defined by a hand-written Julia file (prologue, structs, ...), by a cheap regex scan."""
function defined_names(text::AbstractString)
    names = Set{String}()
    for m in eachmatch(r"(?m)^(?:const|mutable struct|struct|abstract type|primitive type|@enum)\s+(\w+)", text)
        push!(names, m.captures[1])
    end
    for m in eachmatch(r"(?m)^(\w+)\s*=\s*", text)          # PetscInt = Int64 style globals
        push!(names, m.captures[1])
    end
    return names
end

"""
Opaque type declarations for every argument type that is not defined anywhere else.
`XFn` function-pointer types become empty mutable structs, others `Ptr{_n_X}` aliases.
"""
function write_opaque_types(io::IO, names::Vector{String})
    println(io, "# Opaque type declarations for argument types not defined elsewhere ------")
    for t in sort(names)
        if occursin("Fn", t)
            println(io, "mutable struct $t end\n")
        else
            println(io, "mutable struct _n_$t end")
            println(io, "const $t = Ptr{_n_$t}\n")
        end
    end
    println(io, "# -------------------------------------------------------")
end

function write_version(io::IO, version::AbstractString)
    println(io, "# Auto-generated by wrapping/generate.jl — do not edit")
    println(io, "const PETSC_WRAPPERS_VERSION = v\"$version\"")
end

"""prologue.jl up to the include list, followed by a generated include list."""
function write_library_file(io::IO, prologue_text::AbstractString, includes::Vector{Tuple{String,Bool}})
    marker = "# load all generated files"
    idx = findfirst(marker, prologue_text)
    head = idx === nothing ? prologue_text : prologue_text[1:first(idx)-1]
    print(io, head)
    println(io, marker)
    for (f, on) in includes
        println(io, on ? "include(\"$f\")" : "#include(\"$f\")  # excluded, see rules/files.toml")
    end
end
