@enum PetscRegressorLinearType begin
    REGRESSOR_LINEAR_OLS = 0
    REGRESSOR_LINEAR_LASSO = 1
    REGRESSOR_LINEAR_RIDGE = 2
end 

@enum DMFieldContinuity begin
    DMFIELD_VERTEX = 0
    DMFIELD_EDGE = 1
    DMFIELD_FACET = 2
    DMFIELD_CELL = 3
end 

@enum ScatterMode begin
    SCATTER_FORWARD = 0
    SCATTER_REVERSE = 1
    SCATTER_FORWARD_LOCAL = 2
    SCATTER_REVERSE_LOCAL = 3
end 

@enum NormType begin
    NORM_1 = 0
    NORM_2 = 1
    NORM_FROBENIUS = 2
    NORM_INFINITY = 3
    NORM_1_AND_2 = 4
end 

@enum ReductionType begin
    REDUCTION_SUM_REALPART = 10
    REDUCTION_MEAN_REALPART = 11
    REDUCTION_SUM_IMAGINARYPART = 12
    REDUCTION_MEAN_IMAGINARYPART = 13
end 

@enum VecOption begin
    VEC_IGNORE_OFF_PROC_ENTRIES = 0
    VEC_IGNORE_NEGATIVE_INDICES = 1
    VEC_SUBSET_OFF_PROC_ENTRIES = 2
end 

@enum VecOperation begin
    VECOP_DUPLICATE = 0
    VECOP_SET = 10
    VECOP_VIEW = 33
    VECOP_LOAD = 41
    VECOP_VIEWNATIVE = 68
    VECOP_LOADNATIVE = 69
end 

@enum VecTaggerCDFMethod begin
    VECTAGGER_CDF_GATHER = 0
    VECTAGGER_CDF_ITERATIVE = 1
    VECTAGGER_CDF_NUM_METHODS = 2
end 

@enum PetscDrawMarkerType begin
    PETSC_DRAW_MARKER_CROSS = 0
    PETSC_DRAW_MARKER_POINT = 1
    PETSC_DRAW_MARKER_PLUS = 2
    PETSC_DRAW_MARKER_CIRCLE = 3
end 

@enum PetscDrawButton begin
    PETSC_BUTTON_NONE = 0
    PETSC_BUTTON_LEFT = 1
    PETSC_BUTTON_CENTER = 2
    PETSC_BUTTON_RIGHT = 3
    PETSC_BUTTON_WHEEL_UP = 4
    PETSC_BUTTON_WHEEL_DOWN = 5
    PETSC_BUTTON_LEFT_SHIFT = 6
    PETSC_BUTTON_CENTER_SHIFT = 7
    PETSC_BUTTON_RIGHT_SHIFT = 8
end 

@enum PetscWeakFormKind begin
    PETSC_WF_OBJECTIVE = 0
    PETSC_WF_F0 = 1
    PETSC_WF_F1 = 2
    PETSC_WF_G0 = 3
    PETSC_WF_G1 = 4
    PETSC_WF_G2 = 5
    PETSC_WF_G3 = 6
    PETSC_WF_GP0 = 7
    PETSC_WF_GP1 = 8
    PETSC_WF_GP2 = 9
    PETSC_WF_GP3 = 10
    PETSC_WF_GT0 = 11
    PETSC_WF_GT1 = 12
    PETSC_WF_GT2 = 13
    PETSC_WF_GT3 = 14
    PETSC_WF_BDF0 = 15
    PETSC_WF_BDF1 = 16
    PETSC_WF_BDG0 = 17
    PETSC_WF_BDG1 = 18
    PETSC_WF_BDG2 = 19
    PETSC_WF_BDG3 = 20
    PETSC_WF_BDGP0 = 21
    PETSC_WF_BDGP1 = 22
    PETSC_WF_BDGP2 = 23
    PETSC_WF_BDGP3 = 24
    PETSC_WF_R = 25
    PETSC_WF_CEED = 26
    PETSC_NUM_WF = 27
end 

@enum DMSwarmType begin
    DMSWARM_BASIC = 0
    DMSWARM_PIC = 1
end 

@enum DMSwarmMigrateType begin
    DMSWARM_MIGRATE_BASIC = 0
    DMSWARM_MIGRATE_DMCELLNSCATTER = 1
    DMSWARM_MIGRATE_DMCELLEXACT = 2
    DMSWARM_MIGRATE_USER = 3
end 

@enum DMSwarmCollectType begin
    DMSWARM_COLLECT_BASIC = 0
    DMSWARM_COLLECT_DMDABOUNDINGBOX = 1
    DMSWARM_COLLECT_GENERAL = 2
    DMSWARM_COLLECT_USER = 3
end 

@enum DMSwarmRemapType begin
    DMSWARM_REMAP_NONE = 0
    DMSWARM_REMAP_PFAK = 1
    DMSWARM_REMAP_COLELLA = 2
end 

@enum DMSwarmPICLayoutType begin
    DMSWARMPIC_LAYOUT_REGULAR = 0
    DMSWARMPIC_LAYOUT_GAUSS = 1
    DMSWARMPIC_LAYOUT_SUBDIVISION = 2
end 

@enum DMStagStencilLocation begin
    DMSTAG_NULL_LOCATION = 0
    DMSTAG_BACK_DOWN_LEFT = 1
    DMSTAG_BACK_DOWN = 2
    DMSTAG_BACK_DOWN_RIGHT = 3
    DMSTAG_BACK_LEFT = 4
    DMSTAG_BACK = 5
    DMSTAG_BACK_RIGHT = 6
    DMSTAG_BACK_UP_LEFT = 7
    DMSTAG_BACK_UP = 8
    DMSTAG_BACK_UP_RIGHT = 9
    DMSTAG_DOWN_LEFT = 10
    DMSTAG_DOWN = 11
    DMSTAG_DOWN_RIGHT = 12
    DMSTAG_LEFT = 13
    DMSTAG_ELEMENT = 14
    DMSTAG_RIGHT = 15
    DMSTAG_UP_LEFT = 16
    DMSTAG_UP = 17
    DMSTAG_UP_RIGHT = 18
    DMSTAG_FRONT_DOWN_LEFT = 19
    DMSTAG_FRONT_DOWN = 20
    DMSTAG_FRONT_DOWN_RIGHT = 21
    DMSTAG_FRONT_LEFT = 22
    DMSTAG_FRONT = 23
    DMSTAG_FRONT_RIGHT = 24
    DMSTAG_FRONT_UP_LEFT = 25
    DMSTAG_FRONT_UP = 26
    DMSTAG_FRONT_UP_RIGHT = 27
end 

@enum DMStagStencilType begin
    DMSTAG_STENCIL_NONE = 0
    DMSTAG_STENCIL_STAR = 1
    DMSTAG_STENCIL_BOX = 2
end 

@enum MatFactorType begin
    MAT_FACTOR_NONE = 0
    MAT_FACTOR_LU = 1
    MAT_FACTOR_CHOLESKY = 2
    MAT_FACTOR_ILU = 3
    MAT_FACTOR_ICC = 4
    MAT_FACTOR_ILUDT = 5
    MAT_FACTOR_QR = 6
    MAT_FACTOR_NUM_TYPES = 7
end 

@enum MatProductType begin
    MATPRODUCT_UNSPECIFIED = 0
    MATPRODUCT_AB = 1
    MATPRODUCT_AtB = 2
    MATPRODUCT_ABt = 3
    MATPRODUCT_PtAP = 4
    MATPRODUCT_RARt = 5
    MATPRODUCT_ABC = 6
end 

@enum MatReuse begin
    MAT_INITIAL_MATRIX = 0
    MAT_REUSE_MATRIX = 1
    MAT_IGNORE_MATRIX = 2
    MAT_INPLACE_MATRIX = 3
end 

@enum MatCreateSubMatrixOption begin
    MAT_DO_NOT_GET_VALUES = 0
    MAT_GET_VALUES = 1
end 

@enum MatStructure begin
    DIFFERENT_NONZERO_PATTERN = 0
    SUBSET_NONZERO_PATTERN = 1
    SAME_NONZERO_PATTERN = 2
    UNKNOWN_NONZERO_PATTERN = 3
end 

@enum MatCompositeMergeType begin
    MAT_COMPOSITE_MERGE_RIGHT = 0
    MAT_COMPOSITE_MERGE_LEFT = 1
end 

@enum MatCompositeType begin
    MAT_COMPOSITE_ADDITIVE = 0
    MAT_COMPOSITE_MULTIPLICATIVE = 1
end 

@enum MatAssemblyType begin
    MAT_FLUSH_ASSEMBLY = 1
    MAT_FINAL_ASSEMBLY = 0
end 

@enum MatOption begin
    MAT_OPTION_MIN = -3
    MAT_UNUSED_NONZERO_LOCATION_ERR = -2
    MAT_ROW_ORIENTED = -1
    MAT_SYMMETRIC = 1
    MAT_STRUCTURALLY_SYMMETRIC = 2
    MAT_FORCE_DIAGONAL_ENTRIES = 3
    MAT_IGNORE_OFF_PROC_ENTRIES = 4
    MAT_USE_HASH_TABLE = 5
    MAT_KEEP_NONZERO_PATTERN = 6
    MAT_IGNORE_ZERO_ENTRIES = 7
    MAT_USE_INODES = 8
    MAT_HERMITIAN = 9
    MAT_SYMMETRY_ETERNAL = 10
    MAT_NEW_NONZERO_LOCATION_ERR = 11
    MAT_IGNORE_LOWER_TRIANGULAR = 12
    MAT_ERROR_LOWER_TRIANGULAR = 13
    MAT_GETROW_UPPERTRIANGULAR = 14
    MAT_SPD = 15
    MAT_NO_OFF_PROC_ZERO_ROWS = 16
    MAT_NO_OFF_PROC_ENTRIES = 17
    MAT_NEW_NONZERO_LOCATIONS = 18
    MAT_NEW_NONZERO_ALLOCATION_ERR = 19
    MAT_SUBSET_OFF_PROC_ENTRIES = 20
    MAT_SUBMAT_SINGLEIS = 21
    MAT_STRUCTURE_ONLY = 22
    MAT_SORTED_FULL = 23
    MAT_FORM_EXPLICIT_TRANSPOSE = 24
    MAT_STRUCTURAL_SYMMETRY_ETERNAL = 25
    MAT_SPD_ETERNAL = 26
    MAT_OPTION_MAX = 27
end 

@enum MatDuplicateOption begin
    MAT_DO_NOT_COPY_VALUES = 0
    MAT_COPY_VALUES = 1
    MAT_SHARE_NONZERO_PATTERN = 2
end 

@enum MatInfoType begin
    MAT_LOCAL = 1
    MAT_GLOBAL_MAX = 2
    MAT_GLOBAL_SUM = 3
end 

@enum MatFactorShiftType begin
    MAT_SHIFT_NONE = 0
    MAT_SHIFT_NONZERO = 1
    MAT_SHIFT_POSITIVE_DEFINITE = 2
    MAT_SHIFT_INBLOCKS = 3
end 

@enum MatFactorError begin
    MAT_FACTOR_NOERROR = 0
    MAT_FACTOR_STRUCT_ZEROPIVOT = 1
    MAT_FACTOR_NUMERIC_ZEROPIVOT = 2
    MAT_FACTOR_OUTMEMORY = 3
    MAT_FACTOR_OTHER = 4
end 

@enum MatFactorSchurStatus begin
    MAT_FACTOR_SCHUR_UNFACTORED = 0
    MAT_FACTOR_SCHUR_FACTORED = 1
    MAT_FACTOR_SCHUR_INVERTED = 2
end 

@enum MatSORType begin
    SOR_FORWARD_SWEEP = 1
    SOR_BACKWARD_SWEEP = 2
    SOR_SYMMETRIC_SWEEP = 3
    SOR_LOCAL_FORWARD_SWEEP = 4
    SOR_LOCAL_BACKWARD_SWEEP = 8
    SOR_LOCAL_SYMMETRIC_SWEEP = 12
    SOR_ZERO_INITIAL_GUESS = 16
    SOR_EISENSTAT = 32
    SOR_APPLY_UPPER = 64
    SOR_APPLY_LOWER = 128
end 

@enum MatColoringWeightType begin
    MAT_COLORING_WEIGHT_RANDOM = 0
    MAT_COLORING_WEIGHT_LEXICAL = 1
    MAT_COLORING_WEIGHT_LF = 2
    MAT_COLORING_WEIGHT_SL = 3
end 

@enum MPChacoGlobalType begin
    MP_CHACO_MULTILEVEL = 1
    MP_CHACO_SPECTRAL = 2
    MP_CHACO_LINEAR = 4
    MP_CHACO_RANDOM = 5
    MP_CHACO_SCATTERED = 6
end 

@enum MPChacoLocalType begin
    MP_CHACO_KERNIGHAN = 1
    MP_CHACO_NONE = 2
end 

@enum MPChacoEigenType begin
    MP_CHACO_LANCZOS = 0
    MP_CHACO_RQI = 1
end 

@enum MPPTScotchStrategyType begin
    MP_PTSCOTCH_DEFAULT = 0
    MP_PTSCOTCH_QUALITY = 1
    MP_PTSCOTCH_SPEED = 2
    MP_PTSCOTCH_BALANCE = 3
    MP_PTSCOTCH_SAFETY = 4
    MP_PTSCOTCH_SCALABILITY = 5
end 

@enum MatOperation begin
    MATOP_SET_VALUES = 0
    MATOP_GET_ROW = 1
    MATOP_RESTORE_ROW = 2
    MATOP_MULT = 3
    MATOP_MULT_ADD = 4
    MATOP_MULT_TRANSPOSE = 5
    MATOP_MULT_TRANSPOSE_ADD = 6
    MATOP_SOLVE = 7
    MATOP_SOLVE_ADD = 8
    MATOP_SOLVE_TRANSPOSE = 9
    MATOP_SOLVE_TRANSPOSE_ADD = 10
    MATOP_LUFACTOR = 11
    MATOP_CHOLESKYFACTOR = 12
    MATOP_SOR = 13
    MATOP_TRANSPOSE = 14
    MATOP_GETINFO = 15
    MATOP_EQUAL = 16
    MATOP_GET_DIAGONAL = 17
    MATOP_DIAGONAL_SCALE = 18
    MATOP_NORM = 19
    MATOP_ASSEMBLY_BEGIN = 20
    MATOP_ASSEMBLY_END = 21
    MATOP_SET_OPTION = 22
    MATOP_ZERO_ENTRIES = 23
    MATOP_ZERO_ROWS = 24
    MATOP_LUFACTOR_SYMBOLIC = 25
    MATOP_LUFACTOR_NUMERIC = 26
    MATOP_CHOLESKY_FACTOR_SYMBOLIC = 27
    MATOP_CHOLESKY_FACTOR_NUMERIC = 28
    MATOP_SETUP = 29
    MATOP_ILUFACTOR_SYMBOLIC = 30
    MATOP_ICCFACTOR_SYMBOLIC = 31
    MATOP_GET_DIAGONAL_BLOCK = 32
    MATOP_SET_INF = 33
    MATOP_DUPLICATE = 34
    MATOP_FORWARD_SOLVE = 35
    MATOP_BACKWARD_SOLVE = 36
    MATOP_ILUFACTOR = 37
    MATOP_ICCFACTOR = 38
    MATOP_AXPY = 39
    MATOP_CREATE_SUBMATRICES = 40
    MATOP_INCREASE_OVERLAP = 41
    MATOP_GET_VALUES = 42
    MATOP_COPY = 43
    MATOP_GET_ROW_MAX = 44
    MATOP_SCALE = 45
    MATOP_SHIFT = 46
    MATOP_DIAGONAL_SET = 47
    MATOP_ZERO_ROWS_COLUMNS = 48
    MATOP_SET_RANDOM = 49
    MATOP_GET_ROW_IJ = 50
    MATOP_RESTORE_ROW_IJ = 51
    MATOP_GET_COLUMN_IJ = 52
    MATOP_RESTORE_COLUMN_IJ = 53
    MATOP_FDCOLORING_CREATE = 54
    MATOP_COLORING_PATCH = 55
    MATOP_SET_UNFACTORED = 56
    MATOP_PERMUTE = 57
    MATOP_SET_VALUES_BLOCKED = 58
    MATOP_CREATE_SUBMATRIX = 59
    MATOP_DESTROY = 60
    MATOP_VIEW = 61
    MATOP_CONVERT_FROM = 62
    MATOP_MATMAT_MULT_SYMBOLIC = 63
    MATOP_MATMAT_MULT_NUMERIC = 64
    MATOP_SET_LOCAL_TO_GLOBAL_MAP = 65
    MATOP_SET_VALUES_LOCAL = 66
    MATOP_ZERO_ROWS_LOCAL = 67
    MATOP_GET_ROW_MAX_ABS = 68
    MATOP_GET_ROW_MIN_ABS = 69
    MATOP_CONVERT = 70
    MATOP_HAS_OPERATION = 71
    MATOP_FD_COLORING_APPLY = 72
    MATOP_SET_FROM_OPTIONS = 73
    MATOP_FIND_ZERO_DIAGONALS = 74
    MATOP_MULT_MULTIPLE = 75
    MATOP_SOLVE_MULTIPLE = 76
    MATOP_GET_INERTIA = 77
    MATOP_LOAD = 78
    MATOP_IS_SYMMETRIC = 79
    MATOP_IS_HERMITIAN = 80
    MATOP_IS_STRUCTURALLY_SYMMETRIC = 81
    MATOP_SET_VALUES_BLOCKEDLOCAL = 82
    MATOP_CREATE_VECS = 83
    MATOP_MAT_MULT_SYMBOLIC = 84
    MATOP_MAT_MULT_NUMERIC = 85
    MATOP_PTAP_NUMERIC = 86
    MATOP_MAT_TRANSPOSE_MULT_SYMBO = 87
    MATOP_MAT_TRANSPOSE_MULT_NUMER = 88
    MATOP_BIND_TO_CPU = 89
    MATOP_PRODUCTSETFROMOPTIONS = 90
    MATOP_PRODUCTSYMBOLIC = 91
    MATOP_PRODUCTNUMERIC = 92
    MATOP_CONJUGATE = 93
    MATOP_VIEW_NATIVE = 94
    MATOP_SET_VALUES_ROW = 95
    MATOP_REAL_PART = 96
    MATOP_IMAGINARY_PART = 97
    MATOP_GET_ROW_UPPER_TRIANGULAR = 98
    MATOP_RESTORE_ROW_UPPER_TRIANG = 99
    MATOP_MAT_SOLVE = 100
    MATOP_MAT_SOLVE_TRANSPOSE = 101
    MATOP_GET_ROW_MIN = 102
    MATOP_GET_COLUMN_VECTOR = 103
    MATOP_MISSING_DIAGONAL = 104
    MATOP_GET_SEQ_NONZERO_STRUCTUR = 105
    MATOP_CREATE = 106
    MATOP_GET_GHOSTS = 107
    MATOP_GET_LOCAL_SUB_MATRIX = 108
    MATOP_RESTORE_LOCALSUB_MATRIX = 109
    MATOP_MULT_DIAGONAL_BLOCK = 110
    MATOP_HERMITIAN_TRANSPOSE = 111
    MATOP_MULT_HERMITIAN_TRANSPOSE = 112
    MATOP_MULT_HERMITIAN_TRANS_ADD = 113
    MATOP_GET_MULTI_PROC_BLOCK = 114
    MATOP_FIND_NONZERO_ROWS = 115
    MATOP_GET_COLUMN_NORMS = 116
    MATOP_INVERT_BLOCK_DIAGONAL = 117
    MATOP_INVERT_VBLOCK_DIAGONAL = 118
    MATOP_CREATE_SUB_MATRICES_MPI = 119
    MATOP_SET_VALUES_BATCH = 120
    MATOP_TRANSPOSE_MAT_MULT_SYMBO = 121
    MATOP_TRANSPOSE_MAT_MULT_NUMER = 122
    MATOP_TRANSPOSE_COLORING_CREAT = 123
    MATOP_TRANS_COLORING_APPLY_SPT = 124
    MATOP_TRANS_COLORING_APPLY_DEN = 125
    MATOP_RART_NUMERIC = 126
    MATOP_SET_BLOCK_SIZES = 127
    MATOP_RESIDUAL = 128
    MATOP_FDCOLORING_SETUP = 129
    MATOP_FIND_OFFBLOCK_ENTRIES = 130
    MATOP_MPICONCATENATESEQ = 131
    MATOP_DESTROYSUBMATRICES = 132
    MATOP_MAT_TRANSPOSE_SOLVE = 133
    MATOP_GET_VALUES_LOCAL = 134
    MATOP_CREATE_GRAPH = 135
    MATOP_TRANSPOSE_SYMBOLIC = 136
    MATOP_ELIMINATE_ZEROS = 137
    MATOP_GET_ROW_SUM_ABS = 138
    MATOP_GET_FACTOR = 139
    MATOP_GET_BLOCK_DIAGONAL = 140
    MATOP_GET_VBLOCK_DIAGONAL = 141
    MATOP_COPY_HASH_TO_XAIJ = 142
    MATOP_GET_CURRENT_MEM_TYPE = 143
    MATOP_ZERO_ROWS_COLUMNS_LOCAL = 144
end 

@enum MatHtoolCompressorType begin
    MAT_HTOOL_COMPRESSOR_SYMPARTIAL_ACA = 0
    MAT_HTOOL_COMPRESSOR_FULL_ACA = 1
    MAT_HTOOL_COMPRESSOR_SVD = 2
end 

@enum MatHtoolClusteringType begin
    MAT_HTOOL_CLUSTERING_PCA_REGULAR = 0
    MAT_HTOOL_CLUSTERING_PCA_GEOMETRIC = 1
    MAT_HTOOL_CLUSTERING_BOUNDING_BOX_1_REGULAR = 2
    MAT_HTOOL_CLUSTERING_BOUNDING_BOX_1_GEOMETRIC = 3
end 

@enum MatSTRUMPACKReordering begin
    MAT_STRUMPACK_NATURAL = 0
    MAT_STRUMPACK_METIS = 1
    MAT_STRUMPACK_PARMETIS = 2
    MAT_STRUMPACK_SCOTCH = 3
    MAT_STRUMPACK_PTSCOTCH = 4
    MAT_STRUMPACK_RCM = 5
    MAT_STRUMPACK_GEOMETRIC = 6
    MAT_STRUMPACK_AMD = 7
    MAT_STRUMPACK_MMD = 8
    MAT_STRUMPACK_AND = 9
    MAT_STRUMPACK_MLF = 10
    MAT_STRUMPACK_SPECTRAL = 11
end 

@enum MatSTRUMPACKCompressionType begin
    MAT_STRUMPACK_COMPRESSION_TYPE_NONE = 0
    MAT_STRUMPACK_COMPRESSION_TYPE_HSS = 1
    MAT_STRUMPACK_COMPRESSION_TYPE_BLR = 2
    MAT_STRUMPACK_COMPRESSION_TYPE_HODLR = 3
    MAT_STRUMPACK_COMPRESSION_TYPE_BLR_HODLR = 4
    MAT_STRUMPACK_COMPRESSION_TYPE_ZFP_BLR_HODLR = 5
    MAT_STRUMPACK_COMPRESSION_TYPE_LOSSLESS = 6
    MAT_STRUMPACK_COMPRESSION_TYPE_LOSSY = 7
end 

@enum MatCUSPARSEStorageFormat begin
    MAT_CUSPARSE_CSR = 0
    MAT_CUSPARSE_ELL = 1
    MAT_CUSPARSE_HYB = 2
end 

@enum MatCUSPARSEFormatOperation begin
    MAT_CUSPARSE_MULT_DIAG = 0
    MAT_CUSPARSE_MULT_OFFDIAG = 1
    MAT_CUSPARSE_MULT = 2
    MAT_CUSPARSE_ALL = 3
end 

@enum MatHIPSPARSEStorageFormat begin
    MAT_HIPSPARSE_CSR = 0
    MAT_HIPSPARSE_ELL = 1
    MAT_HIPSPARSE_HYB = 2
end 

@enum MatHIPSPARSEFormatOperation begin
    MAT_HIPSPARSE_MULT_DIAG = 0
    MAT_HIPSPARSE_MULT_OFFDIAG = 1
    MAT_HIPSPARSE_MULT = 2
    MAT_HIPSPARSE_ALL = 3
end 

@enum SNESNewtonTRFallbackType begin
    SNES_TR_FALLBACK_NEWTON = 0
    SNES_TR_FALLBACK_CAUCHY = 1
    SNES_TR_FALLBACK_DOGLEG = 2
end 

@enum SNESNewtonTRQNType begin
    SNES_TR_QN_NONE = 0
    SNES_TR_QN_SAME = 1
    SNES_TR_QN_DIFFERENT = 2
end 

@enum SNESConvergedReason begin
    SNES_CONVERGED_FNORM_ABS = 2
    SNES_CONVERGED_FNORM_RELATIVE = 3
    SNES_CONVERGED_SNORM_RELATIVE = 4
    SNES_CONVERGED_ITS = 5
    SNES_BREAKOUT_INNER_ITER = 6
    SNES_CONVERGED_USER = 7
    SNES_DIVERGED_FUNCTION_DOMAIN = -1
    SNES_DIVERGED_FUNCTION_COUNT = -2
    SNES_DIVERGED_LINEAR_SOLVE = -3
    SNES_DIVERGED_FNORM_NAN = -4
    SNES_DIVERGED_MAX_IT = -5
    SNES_DIVERGED_LINE_SEARCH = -6
    SNES_DIVERGED_INNER = -7
    SNES_DIVERGED_LOCAL_MIN = -8
    SNES_DIVERGED_DTOL = -9
    SNES_DIVERGED_JACOBIAN_DOMAIN = -10
    SNES_DIVERGED_TR_DELTA = -11
end 

@enum SNESNormSchedule begin
    SNES_NORM_DEFAULT = -1
    SNES_NORM_NONE = 0
    SNES_NORM_ALWAYS = 1
    SNES_NORM_INITIAL_ONLY = 2
    SNES_NORM_FINAL_ONLY = 3
    SNES_NORM_INITIAL_FINAL_ONLY = 4
end 

@enum SNESFunctionType begin
    SNES_FUNCTION_DEFAULT = -1
    SNES_FUNCTION_UNPRECONDITIONED = 0
    SNES_FUNCTION_PRECONDITIONED = 1
end 

@enum SNESLineSearchReason begin
    SNES_LINESEARCH_SUCCEEDED = 0
    SNES_LINESEARCH_FAILED_NANORINF = 1
    SNES_LINESEARCH_FAILED_DOMAIN = 2
    SNES_LINESEARCH_FAILED_REDUCT = 3
    SNES_LINESEARCH_FAILED_USER = 4
    SNES_LINESEARCH_FAILED_FUNCTION = 5
end 

@enum SNESNGMRESRestartType begin
    SNES_NGMRES_RESTART_NONE = 0
    SNES_NGMRES_RESTART_PERIODIC = 1
    SNES_NGMRES_RESTART_DIFFERENCE = 2
end 

@enum SNESNGMRESSelectType begin
    SNES_NGMRES_SELECT_NONE = 0
    SNES_NGMRES_SELECT_DIFFERENCE = 1
    SNES_NGMRES_SELECT_LINESEARCH = 2
end 

@enum SNESNCGType begin
    SNES_NCG_FR = 0
    SNES_NCG_PRP = 1
    SNES_NCG_HS = 2
    SNES_NCG_DY = 3
    SNES_NCG_CD = 4
end 

@enum SNESQNScaleType begin
    SNES_QN_SCALE_DEFAULT = 0
    SNES_QN_SCALE_NONE = 1
    SNES_QN_SCALE_SCALAR = 2
    SNES_QN_SCALE_DIAGONAL = 3
    SNES_QN_SCALE_JACOBIAN = 4
end 

@enum SNESQNRestartType begin
    SNES_QN_RESTART_DEFAULT = 0
    SNES_QN_RESTART_NONE = 1
    SNES_QN_RESTART_POWELL = 2
    SNES_QN_RESTART_PERIODIC = 3
end 

@enum SNESQNType begin
    SNES_QN_LBFGS = 0
    SNES_QN_BROYDEN = 1
    SNES_QN_BADBROYDEN = 2
end 

@enum SNESCompositeType begin
    SNES_COMPOSITE_ADDITIVE = 0
    SNES_COMPOSITE_MULTIPLICATIVE = 1
    SNES_COMPOSITE_ADDITIVEOPTIMAL = 2
end 

@enum SNESFASType begin
    SNES_FAS_MULTIPLICATIVE = 0
    SNES_FAS_ADDITIVE = 1
    SNES_FAS_FULL = 2
    SNES_FAS_KASKADE = 3
end 

@enum SNESNewtonALCorrectionType begin
    SNES_NEWTONAL_CORRECTION_EXACT = 0
    SNES_NEWTONAL_CORRECTION_NORMAL = 1
end 

@enum LandauDeviceType begin
    LANDAU_KOKKOS = 0
    LANDAU_CPU = 1
end 

@enum LandauOMPTimers begin
    LANDAU_EX2_TSSOLVE = 0
    LANDAU_MATRIX_TOTAL = 1
    LANDAU_OPERATOR = 2
    LANDAU_JACOBIAN_COUNT = 3
    LANDAU_JACOBIAN = 4
    LANDAU_MASS = 5
    LANDAU_F_DF = 6
    LANDAU_KERNEL = 7
    KSP_FACTOR = 8
    KSP_SOLVE = 9
    LANDAU_NUM_TIMERS = 10
end 

@enum PetscErrorType begin
    PETSC_ERROR_INITIAL = 0
    PETSC_ERROR_REPEAT = 1
    PETSC_ERROR_IN_CXX = 2
end 

@enum PetscFPTrap begin
    PETSC_FP_TRAP_OFF = 0
    PETSC_FP_TRAP_INDIV = 1
    PETSC_FP_TRAP_FLTOPERR = 2
    PETSC_FP_TRAP_FLTOVF = 4
    PETSC_FP_TRAP_FLTUND = 8
    PETSC_FP_TRAP_FLTDIV = 16
    PETSC_FP_TRAP_FLTINEX = 32
    PETSC_FP_TRAP_ON = 63
end 

@enum DMCopyLabelsMode begin
    DM_COPY_LABELS_REPLACE = 0
    DM_COPY_LABELS_KEEP = 1
    DM_COPY_LABELS_FAIL = 2
end 

@enum KSPChebyshevKind begin
    KSP_CHEBYSHEV_FIRST = 0
    KSP_CHEBYSHEV_FOURTH = 1
    KSP_CHEBYSHEV_OPT_FOURTH = 2
end 

@enum KSPFCDTruncationType begin
    KSP_FCD_TRUNC_TYPE_STANDARD = 0
    KSP_FCD_TRUNC_TYPE_NOTAY = 1
end 

@enum KSPHPDDMType begin
    KSP_HPDDM_TYPE_GMRES = 0
    KSP_HPDDM_TYPE_BGMRES = 1
    KSP_HPDDM_TYPE_CG = 2
    KSP_HPDDM_TYPE_BCG = 3
    KSP_HPDDM_TYPE_GCRODR = 4
    KSP_HPDDM_TYPE_BGCRODR = 5
    KSP_HPDDM_TYPE_BFBCG = 6
    KSP_HPDDM_TYPE_PREONLY = 7
end 

@enum KSPHPDDMPrecision begin
    KSP_HPDDM_PRECISION_HALF = 0
    KSP_HPDDM_PRECISION_SINGLE = 1
    KSP_HPDDM_PRECISION_DOUBLE = 2
    KSP_HPDDM_PRECISION_QUADRUPLE = 3
end 

@enum KSPGMRESCGSRefinementType begin
    KSP_GMRES_CGS_REFINE_NEVER = 0
    KSP_GMRES_CGS_REFINE_IFNEEDED = 1
    KSP_GMRES_CGS_REFINE_ALWAYS = 2
end 

@enum KSPNormType begin
    KSP_NORM_DEFAULT = -1
    KSP_NORM_NONE = 0
    KSP_NORM_PRECONDITIONED = 1
    KSP_NORM_UNPRECONDITIONED = 2
    KSP_NORM_NATURAL = 3
end 

@enum KSPCGType begin
    KSP_CG_SYMMETRIC = 0
    KSP_CG_HERMITIAN = 1
end 

@enum MatSchurComplementAinvType begin
    MAT_SCHUR_COMPLEMENT_AINV_DIAG = 0
    MAT_SCHUR_COMPLEMENT_AINV_LUMP = 1
    MAT_SCHUR_COMPLEMENT_AINV_BLOCK_DIAG = 2
    MAT_SCHUR_COMPLEMENT_AINV_FULL = 3
end 

@enum MatLMVMMultAlgorithm begin
    MAT_LMVM_MULT_RECURSIVE = 0
    MAT_LMVM_MULT_DENSE = 1
    MAT_LMVM_MULT_COMPACT_DENSE = 2
end 

@enum MatLMVMSymBroydenScaleType begin
    MAT_LMVM_SYMBROYDEN_SCALE_NONE = 0
    MAT_LMVM_SYMBROYDEN_SCALE_SCALAR = 1
    MAT_LMVM_SYMBROYDEN_SCALE_DIAGONAL = 2
    MAT_LMVM_SYMBROYDEN_SCALE_USER = 3
    MAT_LMVM_SYMBROYDEN_SCALE_DECIDE = 4
end 

@enum MatLMVMDenseType begin
    MAT_LMVM_DENSE_REORDER = 0
    MAT_LMVM_DENSE_INPLACE = 1
end 

@enum ISInfo begin
    IS_INFO_MIN = -1
    IS_SORTED = 0
    IS_UNIQUE = 1
    IS_PERMUTATION = 2
    IS_INTERVAL = 3
    IS_IDENTITY = 4
    IS_INFO_MAX = 5
end 

@enum ISInfoType begin
    IS_LOCAL = 0
    IS_GLOBAL = 1
end 

@enum ISGlobalToLocalMappingMode begin
    IS_GTOLM_MASK = 0
    IS_GTOLM_DROP = 1
end 

@enum ISColoringType begin
    IS_COLORING_GLOBAL = 0
    IS_COLORING_LOCAL = 1
end 

@enum DMPlexInterpolatedFlag begin
    DMPLEX_INTERPOLATED_INVALID = -1
    DMPLEX_INTERPOLATED_NONE = 0
    DMPLEX_INTERPOLATED_PARTIAL = 1
    DMPLEX_INTERPOLATED_MIXED = 2
    DMPLEX_INTERPOLATED_FULL = 3
end 

@enum DMPlexTPSType begin
    DMPLEX_TPS_SCHWARZ_P = 0
    DMPLEX_TPS_GYROID = 1
end 

@enum TSProblemType begin
    TS_LINEAR = 0
    TS_NONLINEAR = 1
end 

@enum TSEquationType begin
    TS_EQ_UNSPECIFIED = -1
    TS_EQ_EXPLICIT = 0
    TS_EQ_ODE_EXPLICIT = 1
    TS_EQ_DAE_SEMI_EXPLICIT_INDEX1 = 100
    TS_EQ_DAE_SEMI_EXPLICIT_INDEX2 = 200
    TS_EQ_DAE_SEMI_EXPLICIT_INDEX3 = 300
    TS_EQ_DAE_SEMI_EXPLICIT_INDEXHI = 500
    TS_EQ_IMPLICIT = 1000
    TS_EQ_ODE_IMPLICIT = 1001
    TS_EQ_DAE_IMPLICIT_INDEX1 = 1100
    TS_EQ_DAE_IMPLICIT_INDEX2 = 1200
    TS_EQ_DAE_IMPLICIT_INDEX3 = 1300
    TS_EQ_DAE_IMPLICIT_INDEXHI = 1500
end 

@enum TSConvergedReason begin
    TS_CONVERGED_ITERATING = 0
    TS_CONVERGED_TIME = 1
    TS_CONVERGED_ITS = 2
    TS_CONVERGED_USER = 3
    TS_CONVERGED_EVENT = 4
    TS_CONVERGED_PSEUDO_FATOL = 5
    TS_CONVERGED_PSEUDO_FRTOL = 6
    TS_DIVERGED_NONLINEAR_SOLVE = -1
    TS_DIVERGED_STEP_REJECTED = -2
    TSFORWARD_DIVERGED_LINEAR_SOLVE = -3
    TSADJOINT_DIVERGED_LINEAR_SOLVE = -4
end 

@enum TSExactFinalTimeOption begin
    TS_EXACTFINALTIME_UNSPECIFIED = 0
    TS_EXACTFINALTIME_STEPOVER = 1
    TS_EXACTFINALTIME_INTERPOLATE = 2
    TS_EXACTFINALTIME_MATCHSTEP = 3
end 

@enum TSTrajectoryMemoryType begin
    TJ_REVOLVE = 0
    TJ_CAMS = 1
    TJ_PETSC = 2
end 

@enum TSDGType begin
    TS_DG_GONZALEZ = 0
    TS_DG_AVERAGE = 1
    TS_DG_NONE = 2
end 

@enum TSSundialsLmmType begin
    SUNDIALS_ADAMS = 1
    SUNDIALS_BDF = 2
end 

@enum TSSundialsGramSchmidtType begin
    SUNDIALS_MODIFIED_GS = 1
    SUNDIALS_CLASSICAL_GS = 2
end 

@enum PetscScalarPrecision begin
    PETSC_SCALAR_DOUBLE = 0
    PETSC_SCALAR_SINGLE = 1
    PETSC_SCALAR_LONG_DOUBLE = 2
    PETSC_SCALAR_HALF = 3
end 

@enum DMBoundaryType begin
    DM_BOUNDARY_NONE = 0
    DM_BOUNDARY_GHOSTED = 1
    DM_BOUNDARY_MIRROR = 2
    DM_BOUNDARY_PERIODIC = 3
    DM_BOUNDARY_TWIST = 4
end 

@enum DMBoundaryConditionType begin
    DM_BC_ESSENTIAL = 1
    DM_BC_ESSENTIAL_FIELD = 5
    DM_BC_NATURAL = 2
    DM_BC_NATURAL_FIELD = 6
    DM_BC_ESSENTIAL_BD_FIELD = 9
    DM_BC_NATURAL_RIEMANN = 10
    DM_BC_LOWER_BOUND = 4
    DM_BC_UPPER_BOUND = 8
end 

@enum DMPointLocationType begin
    DM_POINTLOCATION_NONE = 0
    DM_POINTLOCATION_NEAREST = 1
    DM_POINTLOCATION_REMOVE = 2
end 

@enum DMBlockingType begin
    DM_BLOCKING_TOPOLOGICAL_POINT = 0
    DM_BLOCKING_FIELD_NODE = 1
end 

@enum DMAdaptationStrategy begin
    DM_ADAPTATION_INITIAL = 0
    DM_ADAPTATION_SEQUENTIAL = 1
    DM_ADAPTATION_MULTILEVEL = 2
end 

@enum DMAdaptationCriterion begin
    DM_ADAPTATION_NONE = 0
    DM_ADAPTATION_REFINE = 1
    DM_ADAPTATION_LABEL = 2
    DM_ADAPTATION_METRIC = 3
end 

@enum DMAdaptFlag begin
    DM_ADAPT_DETERMINE = PETSC_DETERMINE
    DM_ADAPT_KEEP = 0
    DM_ADAPT_REFINE = 1
    DM_ADAPT_COARSEN = 2
    DM_ADAPT_COARSEN_LAST = 3
    DM_ADAPT_RESERVED_COUNT = 4
end 

@enum DMDirection begin
    DM_X = 0
    DM_Y = 1
    DM_Z = 2
end 

@enum DMEnclosureType begin
    DM_ENC_EQUALITY = 0
    DM_ENC_SUPERMESH = 1
    DM_ENC_SUBMESH = 2
    DM_ENC_NONE = 3
    DM_ENC_UNKNOWN = 4
end 

@enum DMPolytopeType begin
    DM_POLYTOPE_POINT = 0
    DM_POLYTOPE_SEGMENT = 1
    DM_POLYTOPE_POINT_PRISM_TENSOR = 2
    DM_POLYTOPE_TRIANGLE = 3
    DM_POLYTOPE_QUADRILATERAL = 4
    DM_POLYTOPE_SEG_PRISM_TENSOR = 5
    DM_POLYTOPE_TETRAHEDRON = 6
    DM_POLYTOPE_HEXAHEDRON = 7
    DM_POLYTOPE_TRI_PRISM = 8
    DM_POLYTOPE_TRI_PRISM_TENSOR = 9
    DM_POLYTOPE_QUAD_PRISM_TENSOR = 10
    DM_POLYTOPE_PYRAMID = 11
    DM_POLYTOPE_FV_GHOST = 12
    DM_POLYTOPE_INTERIOR_GHOST = 13
    DM_POLYTOPE_UNKNOWN = 14
    DM_POLYTOPE_UNKNOWN_CELL = 15
    DM_POLYTOPE_UNKNOWN_FACE = 16
    DM_NUM_POLYTOPES = 17
end 

@enum PetscUnit begin
    PETSC_UNIT_LENGTH = 0
    PETSC_UNIT_MASS = 1
    PETSC_UNIT_TIME = 2
    PETSC_UNIT_CURRENT = 3
    PETSC_UNIT_TEMPERATURE = 4
    PETSC_UNIT_AMOUNT = 5
    PETSC_UNIT_LUMINOSITY = 6
    NUM_PETSC_UNITS = 7
end 

@enum DMReorderDefaultFlag begin
    DM_REORDER_DEFAULT_NOTSET = -1
    DM_REORDER_DEFAULT_FALSE = 0
    DM_REORDER_DEFAULT_TRUE = 1
end 

@enum PetscOffloadMask begin
    PETSC_OFFLOAD_UNALLOCATED = 0
    PETSC_OFFLOAD_CPU = 1
    PETSC_OFFLOAD_GPU = 2
    PETSC_OFFLOAD_BOTH = 3
end 

@enum PetscDeviceInitType begin
    PETSC_DEVICE_INIT_NONE = 0
    PETSC_DEVICE_INIT_LAZY = 1
    PETSC_DEVICE_INIT_EAGER = 2
end 

@enum PetscDeviceType begin
    PETSC_DEVICE_HOST = 0
    PETSC_DEVICE_CUDA = 1
    PETSC_DEVICE_HIP = 2
    PETSC_DEVICE_SYCL = 3
    PETSC_DEVICE_MAX = 4
end 

@enum PetscDeviceAttribute begin
    PETSC_DEVICE_ATTR_SIZE_T_SHARED_MEM_PER_BLOCK = 0
    PETSC_DEVICE_ATTR_MAX = 1
end 

@enum PetscStreamType begin
    PETSC_STREAM_DEFAULT = 0
    PETSC_STREAM_NONBLOCKING = 1
    PETSC_STREAM_DEFAULT_WITH_BARRIER = 2
    PETSC_STREAM_NONBLOCKING_WITH_BARRIER = 3
    PETSC_STREAM_MAX = 4
end 

@enum PetscDeviceContextJoinMode begin
    PETSC_DEVICE_CONTEXT_JOIN_DESTROY = 0
    PETSC_DEVICE_CONTEXT_JOIN_SYNC = 1
    PETSC_DEVICE_CONTEXT_JOIN_NO_SYNC = 2
end 

@enum PetscDeviceCopyMode begin
    PETSC_DEVICE_COPY_HTOH = 0
    PETSC_DEVICE_COPY_DTOH = 1
    PETSC_DEVICE_COPY_HTOD = 2
    PETSC_DEVICE_COPY_DTOD = 3
    PETSC_DEVICE_COPY_AUTO = 4
end 

@enum PetscMemoryAccessMode begin
    PETSC_MEMORY_ACCESS_READ = 1
    PETSC_MEMORY_ACCESS_WRITE = 2
    PETSC_MEMORY_ACCESS_READ_WRITE = 3 
end 

@enum MoabReadMode begin
    READ_PART = 0
    READ_DELETE = 1
    BCAST_DELETE = 2
end 

@enum MoabWriteMode begin
    WRITE_PART = 0
    FORMAT = 1
end 

@enum PetscPartitionerMultistageStrategy begin
    PETSCPARTITIONER_MS_STRATEGY_NODE = 0
    PETSCPARTITIONER_MS_STRATEGY_MSECTION = 1
end 

@enum PCSide begin
    PC_SIDE_DEFAULT = -1
    PC_LEFT = 0
    PC_RIGHT = 1
    PC_SYMMETRIC = 2
end 

@enum PCRichardsonConvergedReason begin
    PCRICHARDSON_NOT_SET = 0
    PCRICHARDSON_CONVERGED_RTOL = 2
    PCRICHARDSON_CONVERGED_ATOL = 3
    PCRICHARDSON_CONVERGED_ITS = 4
    PCRICHARDSON_DIVERGED_DTOL = -4
end 

@enum PCJacobiType begin
    PC_JACOBI_DIAGONAL = 0
    PC_JACOBI_ROWL1 = 1
    PC_JACOBI_ROWMAX = 2
    PC_JACOBI_ROWSUM = 3
end 

@enum PCASMType begin
    PC_ASM_BASIC = 3
    PC_ASM_RESTRICT = 1
    PC_ASM_INTERPOLATE = 2
    PC_ASM_NONE = 0
end 

@enum PCGASMType begin
    PC_GASM_BASIC = 3
    PC_GASM_RESTRICT = 1
    PC_GASM_INTERPOLATE = 2
    PC_GASM_NONE = 0
end 

@enum PCCompositeType begin
    PC_COMPOSITE_ADDITIVE = 0
    PC_COMPOSITE_MULTIPLICATIVE = 1
    PC_COMPOSITE_SYMMETRIC_MULTIPLICATIVE = 2
    PC_COMPOSITE_SPECIAL = 3
    PC_COMPOSITE_SCHUR = 4
    PC_COMPOSITE_GKB = 5
end 

@enum PCFieldSplitSchurPreType begin
    PC_FIELDSPLIT_SCHUR_PRE_SELF = 0
    PC_FIELDSPLIT_SCHUR_PRE_SELFP = 1
    PC_FIELDSPLIT_SCHUR_PRE_A11 = 2
    PC_FIELDSPLIT_SCHUR_PRE_USER = 3
    PC_FIELDSPLIT_SCHUR_PRE_FULL = 4
end 

@enum PCFieldSplitSchurFactType begin
    PC_FIELDSPLIT_SCHUR_FACT_DIAG = 0
    PC_FIELDSPLIT_SCHUR_FACT_LOWER = 1
    PC_FIELDSPLIT_SCHUR_FACT_UPPER = 2
    PC_FIELDSPLIT_SCHUR_FACT_FULL = 3
end 

@enum PCPARMSGlobalType begin
    PC_PARMS_GLOBAL_RAS = 0
    PC_PARMS_GLOBAL_SCHUR = 1
    PC_PARMS_GLOBAL_BJ = 2
end 

@enum PCPARMSLocalType begin
    PC_PARMS_LOCAL_ILU0 = 0
    PC_PARMS_LOCAL_ILUK = 1
    PC_PARMS_LOCAL_ILUT = 2
    PC_PARMS_LOCAL_ARMS = 3
end 

@enum PCMGType begin
    PC_MG_MULTIPLICATIVE = 0
    PC_MG_ADDITIVE = 1
    PC_MG_FULL = 2
    PC_MG_KASKADE = 3
end 

@enum PCMGCycleType begin
    PC_MG_CYCLE_V = 1
    PC_MG_CYCLE_W = 2
end 

@enum PCMGGalerkinType begin
    PC_MG_GALERKIN_BOTH = 0
    PC_MG_GALERKIN_PMAT = 1
    PC_MG_GALERKIN_MAT = 2
    PC_MG_GALERKIN_NONE = 3
    PC_MG_GALERKIN_EXTERNAL = 4
end 

@enum PCExoticType begin
    PC_EXOTIC_FACE = 0
    PC_EXOTIC_WIREBASKET = 1
end 

@enum PCBDDCInterfaceExtType begin
    PC_BDDC_INTERFACE_EXT_DIRICHLET = 0
    PC_BDDC_INTERFACE_EXT_LUMP = 1
end 

@enum PCMGCoarseSpaceType begin
    PCMG_ADAPT_NONE = 0
    PCMG_ADAPT_POLYNOMIAL = 1
    PCMG_ADAPT_HARMONIC = 2
    PCMG_ADAPT_EIGENVECTOR = 3
    PCMG_ADAPT_GENERALIZED_EIGENVECTOR = 4
    PCMG_ADAPT_GDSW = 5
end 

@enum PCPatchConstructType begin
    PC_PATCH_STAR = 0
    PC_PATCH_VANKA = 1
    PC_PATCH_PARDECOMP = 2
    PC_PATCH_USER = 3
    PC_PATCH_PYTHON = 4
end 

@enum PCDeflationSpaceType begin
    PC_DEFLATION_SPACE_HAAR = 0
    PC_DEFLATION_SPACE_DB2 = 1
    PC_DEFLATION_SPACE_DB4 = 2
    PC_DEFLATION_SPACE_DB8 = 3
    PC_DEFLATION_SPACE_DB16 = 4
    PC_DEFLATION_SPACE_BIORTH22 = 5
    PC_DEFLATION_SPACE_MEYER = 6
    PC_DEFLATION_SPACE_AGGREGATION = 7
    PC_DEFLATION_SPACE_USER = 8
end 

@enum PCHPDDMCoarseCorrectionType begin
    PC_HPDDM_COARSE_CORRECTION_DEFLATED = 0
    PC_HPDDM_COARSE_CORRECTION_ADDITIVE = 1
    PC_HPDDM_COARSE_CORRECTION_BALANCED = 2
    PC_HPDDM_COARSE_CORRECTION_NONE = 3
end 

@enum PCHPDDMSchurPreType begin
    PC_HPDDM_SCHUR_PRE_LEAST_SQUARES = 0
    PC_HPDDM_SCHUR_PRE_GENEO = 1
end 

@enum PCFailedReason begin
    PC_SETUP_ERROR = -1
    PC_NOERROR = 0
    PC_FACTOR_STRUCT_ZEROPIVOT = 1
    PC_FACTOR_NUMERIC_ZEROPIVOT = 2
    PC_FACTOR_OUTMEMORY = 3
    PC_FACTOR_OTHER = 4
    PC_INCONSISTENT_RHS = 5
    PC_SUBPC_ERROR = 6
end 

@enum PCGAMGLayoutType begin
    PCGAMG_LAYOUT_COMPACT = 0
    PCGAMG_LAYOUT_SPREAD = 1
end 

@enum PetscFEJacobianType begin
    PETSCFE_JACOBIAN = 0
    PETSCFE_JACOBIAN_PRE = 1
    PETSCFE_JACOBIAN_DYN = 2
end 

@enum PetscFEGeomMode begin
    PETSC_FEGEOM_BASIC = 0
    PETSC_FEGEOM_EMBEDDED = 1
    PETSC_FEGEOM_BOUNDARY = 2
    PETSC_FEGEOM_COHESIVE = 3
end 

@enum PetscInfoCommFlag begin
    PETSC_INFO_COMM_ALL = -1
    PETSC_INFO_COMM_NO_SELF = 0
    PETSC_INFO_COMM_ONLY_SELF = 1
end 

@enum PetscEnum begin
    ENUM_DUMMY = 0
end 

@enum PetscBool3 begin
    PETSC_BOOL3_FALSE = 0
    PETSC_BOOL3_TRUE = 1
    PETSC_BOOL3_UNKNOWN = -1 
end 

@enum PetscCopyMode begin
    PETSC_COPY_VALUES = 0
    PETSC_OWN_POINTER = 1
    PETSC_USE_POINTER = 2
end 

@enum PetscDataType begin
    PETSC_DATATYPE_UNKNOWN = 0
    PETSC_DOUBLE = 1
    PETSC_COMPLEX = 2
    PETSC_LONG = 3
    PETSC_SHORT = 4
    PETSC_FLOAT = 5
    PETSC_CHAR = 6
    PETSC_BIT_LOGICAL = 7
    PETSC_ENUM = 8
    PETSC_BOOL = 9
    PETSC___FLOAT128 = 10
    PETSC_OBJECT = 11
    PETSC_FUNCTION = 12
    PETSC_STRING = 13
    PETSC___FP16 = 14
    PETSC_STRUCT = 15
    PETSC_INT = 16
    PETSC_INT64 = 17
    PETSC_COUNT = 18
    PETSC_INT32 = 19
end 

@enum PetscFileMode begin
    FILE_MODE_UNDEFINED = -1
    FILE_MODE_READ = 0
    FILE_MODE_WRITE = 1
    FILE_MODE_APPEND = 2
    FILE_MODE_UPDATE = 3
    FILE_MODE_APPEND_UPDATE = 4
end 

@enum PetscDLMode begin
    PETSC_DL_DECIDE = 0
    PETSC_DL_NOW = 1
    PETSC_DL_LOCAL = 2
end 

@enum PetscBinarySeekType begin
    PETSC_BINARY_SEEK_SET = 0
    PETSC_BINARY_SEEK_CUR = 1
    PETSC_BINARY_SEEK_END = 2
end 

@enum PetscBuildTwoSidedType begin
    PETSC_BUILDTWOSIDED_NOTSET = -1
    PETSC_BUILDTWOSIDED_ALLREDUCE = 0
    PETSC_BUILDTWOSIDED_IBARRIER = 1
    PETSC_BUILDTWOSIDED_REDSCATTER = 2 
end 

@enum InsertMode begin
    NOT_SET_VALUES = 0
    INSERT_VALUES = 1
    ADD_VALUES = 2
    MAX_VALUES = 3
    MIN_VALUES = 4
    INSERT_ALL_VALUES = 5
    ADD_ALL_VALUES = 6
    INSERT_BC_VALUES = 7
    ADD_BC_VALUES = 8
end 

@enum PetscSubcommType begin
    PETSC_SUBCOMM_GENERAL = 0
    PETSC_SUBCOMM_CONTIGUOUS = 1
    PETSC_SUBCOMM_INTERLACED = 2
end 

@enum PetscGaussLobattoLegendreCreateType begin
    PETSCGAUSSLOBATTOLEGENDRE_VIA_LINEAR_ALGEBRA = 0
    PETSCGAUSSLOBATTOLEGENDRE_VIA_NEWTON = 1
end 

@enum PetscDTNodeType begin
    PETSCDTNODES_DEFAULT = -1
    PETSCDTNODES_GAUSSJACOBI = 0
    PETSCDTNODES_EQUISPACED = 1
    PETSCDTNODES_TANHSINH = 2
end 

@enum PetscDTSimplexQuadratureType begin
    PETSCDTSIMPLEXQUAD_DEFAULT = -1
    PETSCDTSIMPLEXQUAD_CONIC = 0
    PETSCDTSIMPLEXQUAD_MINSYM = 1
end 

@enum DTProbDensityType begin
    DTPROB_DENSITY_CONSTANT = 0
    DTPROB_DENSITY_GAUSSIAN = 1
    DTPROB_DENSITY_MAXWELL_BOLTZMANN = 2
    DTPROB_NUM_DENSITY = 3
end 

@enum TaoSubsetType begin
    TAO_SUBSET_SUBVEC = 0
    TAO_SUBSET_MASK = 1
    TAO_SUBSET_MATRIXFREE = 2
end 

@enum TaoADMMUpdateType begin
    TAO_ADMM_UPDATE_BASIC = 0
    TAO_ADMM_UPDATE_ADAPTIVE = 1
    TAO_ADMM_UPDATE_ADAPTIVE_RELAXED = 2
end 

@enum TaoADMMRegularizerType begin
    TAO_ADMM_REGULARIZER_USER = 0
    TAO_ADMM_REGULARIZER_SOFT_THRESH = 1
end 

@enum TaoALMMType begin
    TAO_ALMM_CLASSIC = 0
    TAO_ALMM_PHR = 1
end 

@enum TaoBNCGType begin
    TAO_BNCG_GD = 0
    TAO_BNCG_PCGD = 1
    TAO_BNCG_HS = 2
    TAO_BNCG_FR = 3
    TAO_BNCG_PRP = 4
    TAO_BNCG_PRP_PLUS = 5
    TAO_BNCG_DY = 6
    TAO_BNCG_HZ = 7
    TAO_BNCG_DK = 8
    TAO_BNCG_KD = 9
    TAO_BNCG_SSML_BFGS = 10
    TAO_BNCG_SSML_DFP = 11
    TAO_BNCG_SSML_BRDN = 12
end 

@enum TaoConvergedReason begin
    TAO_CONVERGED_GATOL = 3
    TAO_CONVERGED_GRTOL = 4
    TAO_CONVERGED_GTTOL = 5
    TAO_CONVERGED_STEPTOL = 6
    TAO_CONVERGED_MINF = 7
    TAO_CONVERGED_USER = 8
    TAO_DIVERGED_MAXITS = -2
    TAO_DIVERGED_NAN = -4
    TAO_DIVERGED_MAXFCN = -5
    TAO_DIVERGED_LS_FAILURE = -6
    TAO_DIVERGED_TR_REDUCTION = -7
    TAO_DIVERGED_USER = -8
    TAO_CONTINUE_ITERATING = 0
end 

@enum TaoBRGNRegularizationType begin
    TAOBRGN_REGULARIZATION_USER = 0
    TAOBRGN_REGULARIZATION_L2PROX = 1
    TAOBRGN_REGULARIZATION_L2PURE = 2
    TAOBRGN_REGULARIZATION_L1DICT = 3
    TAOBRGN_REGULARIZATION_LM = 4
end 

@enum PetscViewerGLVisType begin
    PETSC_VIEWER_GLVIS_DUMP = 0
    PETSC_VIEWER_GLVIS_SOCKET = 1
end 

@enum PetscViewerFormat begin
    PETSC_VIEWER_DEFAULT = 0
    PETSC_VIEWER_ASCII_MATLAB = 1
    PETSC_VIEWER_ASCII_MATHEMATICA = 2
    PETSC_VIEWER_ASCII_IMPL = 3
    PETSC_VIEWER_ASCII_INFO = 4
    PETSC_VIEWER_ASCII_INFO_DETAIL = 5
    PETSC_VIEWER_ASCII_COMMON = 6
    PETSC_VIEWER_ASCII_SYMMODU = 7
    PETSC_VIEWER_ASCII_INDEX = 8
    PETSC_VIEWER_ASCII_DENSE = 9
    PETSC_VIEWER_ASCII_MATRIXMARKET = 10
    PETSC_VIEWER_ASCII_PCICE = 11
    PETSC_VIEWER_ASCII_PYTHON = 12
    PETSC_VIEWER_ASCII_FACTOR_INFO = 13
    PETSC_VIEWER_ASCII_LATEX = 14
    PETSC_VIEWER_ASCII_XML = 15
    PETSC_VIEWER_ASCII_FLAMEGRAPH = 16
    PETSC_VIEWER_ASCII_GLVIS = 17
    PETSC_VIEWER_ASCII_CSV = 18
    PETSC_VIEWER_DRAW_BASIC = 19
    PETSC_VIEWER_DRAW_LG = 20
    PETSC_VIEWER_DRAW_LG_XRANGE = 21
    PETSC_VIEWER_DRAW_CONTOUR = 22
    PETSC_VIEWER_DRAW_PORTS = 23
    PETSC_VIEWER_VTK_VTS = 24
    PETSC_VIEWER_VTK_VTR = 25
    PETSC_VIEWER_VTK_VTU = 26
    PETSC_VIEWER_BINARY_MATLAB = 27
    PETSC_VIEWER_NATIVE = 28
    PETSC_VIEWER_HDF5_PETSC = 29
    PETSC_VIEWER_HDF5_VIZ = 30
    PETSC_VIEWER_HDF5_XDMF = 31
    PETSC_VIEWER_HDF5_MAT = 32
    PETSC_VIEWER_NOFORMAT = 33
    PETSC_VIEWER_LOAD_BALANCE = 34
    PETSC_VIEWER_FAILED = 35
    PETSC_VIEWER_ALL = 36
end 

@enum PetscViewerVTKFieldType begin
    PETSC_VTK_INVALID = 0
    PETSC_VTK_POINT_FIELD = 1
    PETSC_VTK_POINT_VECTOR_FIELD = 2
    PETSC_VTK_CELL_FIELD = 3
    PETSC_VTK_CELL_VECTOR_FIELD = 4
end 

@enum PetscSFDirection begin
    PETSCSF_ROOT2LEAF = 0
    PETSCSF_LEAF2ROOT = 1
end 

@enum PetscSFOperation begin
    PETSCSF_BCAST = 0
    PETSCSF_REDUCE = 1
    PETSCSF_FETCH = 2
end 

@enum PetscSFBackend begin
    PETSCSF_BACKEND_INVALID = 0
    PETSCSF_BACKEND_CUDA = 1
    PETSCSF_BACKEND_HIP = 2
    PETSCSF_BACKEND_KOKKOS = 3
end 

@enum TaoLineSearchConvergedReason begin
    TAOLINESEARCH_FAILED_INFORNAN = -1
    TAOLINESEARCH_FAILED_BADPARAMETER = -2
    TAOLINESEARCH_FAILED_ASCENT = -3
    TAOLINESEARCH_CONTINUE_ITERATING = 0
    TAOLINESEARCH_SUCCESS = 1
    TAOLINESEARCH_SUCCESS_USER = 2
    TAOLINESEARCH_HALTED_OTHER = 3
    TAOLINESEARCH_HALTED_MAXFCN = 4
    TAOLINESEARCH_HALTED_UPPERBOUND = 5
    TAOLINESEARCH_HALTED_LOWERBOUND = 6
    TAOLINESEARCH_HALTED_RTOL = 7
    TAOLINESEARCH_HALTED_USER = 8
end 

@enum PetscDualSpaceReferenceCell begin
    PETSCDUALSPACE_REFCELL_SIMPLEX = 0
    PETSCDUALSPACE_REFCELL_TENSOR = 1
end 

@enum PetscDualSpaceTransformType begin
    IDENTITY_TRANSFORM = 0
    COVARIANT_PIOLA_TRANSFORM = 1
    CONTRAVARIANT_PIOLA_TRANSFORM = 2
end 

@enum PetscOptionSource begin
    PETSC_OPT_CODE = 0
    PETSC_OPT_COMMAND_LINE = 1
    PETSC_OPT_FILE = 2
    PETSC_OPT_ENVIRONMENT = 3
    NUM_PETSC_OPT_SOURCE = 4
end 

@enum PetscOptionType begin
    OPTION_INT = 0
    OPTION_BOOL = 1
    OPTION_REAL = 2
    OPTION_FLIST = 3
    OPTION_STRING = 4
    OPTION_REAL_ARRAY = 5
    OPTION_SCALAR_ARRAY = 6
    OPTION_HEAD = 7
    OPTION_INT_ARRAY = 8
    OPTION_ELIST = 9
    OPTION_BOOL_ARRAY = 10
    OPTION_STRING_ARRAY = 11
end 

@enum PetscSFPattern begin
    PETSCSF_PATTERN_GENERAL = 0
    PETSCSF_PATTERN_ALLGATHER = 1
    PETSCSF_PATTERN_GATHER = 2
    PETSCSF_PATTERN_ALLTOALL = 3
end 

@enum PetscSFWindowSyncType begin
    PETSCSF_WINDOW_SYNC_FENCE = 0
    PETSCSF_WINDOW_SYNC_LOCK = 1
    PETSCSF_WINDOW_SYNC_ACTIVE = 2
end 

@enum PetscSFWindowFlavorType begin
    PETSCSF_WINDOW_FLAVOR_CREATE = 0
    PETSCSF_WINDOW_FLAVOR_DYNAMIC = 1
    PETSCSF_WINDOW_FLAVOR_ALLOCATE = 2
    PETSCSF_WINDOW_FLAVOR_SHARED = 3
end 

@enum PetscSFDuplicateOption begin
    PETSCSF_DUPLICATE_CONFONLY = 0
    PETSCSF_DUPLICATE_RANKS = 1
    PETSCSF_DUPLICATE_GRAPH = 2
end 

@enum PetscSFConcatenateRootMode begin
    PETSCSF_CONCATENATE_ROOTMODE_LOCAL = 0
    PETSCSF_CONCATENATE_ROOTMODE_SHARED = 1
    PETSCSF_CONCATENATE_ROOTMODE_GLOBAL = 2
end 

@enum DMDAStencilType begin
    DMDA_STENCIL_STAR = 0
    DMDA_STENCIL_BOX = 1
end 

@enum DMDAInterpolationType begin
    DMDA_Q0 = 0
    DMDA_Q1 = 1
end 

@enum DMDAElementType begin
    DMDA_ELEMENT_P1 = 0
    DMDA_ELEMENT_Q1 = 1
end 

@enum PetscDiscType begin
    PETSC_DISC_NONE = 0
    PETSC_DISC_FE = 1
    PETSC_DISC_FV = 2
end 

@enum DMPlexShape begin
    DM_SHAPE_BOX = 0
    DM_SHAPE_BOX_SURFACE = 1
    DM_SHAPE_BALL = 2
    DM_SHAPE_SPHERE = 3
    DM_SHAPE_CYLINDER = 4
    DM_SHAPE_SCHWARZ_P = 5
    DM_SHAPE_GYROID = 6
    DM_SHAPE_DOUBLET = 7
    DM_SHAPE_ANNULUS = 8
    DM_SHAPE_HYPERCUBIC = 9
    DM_SHAPE_ZBOX = 10
    DM_SHAPE_UNKNOWN = 11
end 

@enum DMPlexCoordMap begin
    DM_COORD_MAP_NONE = 0
    DM_COORD_MAP_SHEAR = 1
    DM_COORD_MAP_FLARE = 2
    DM_COORD_MAP_ANNULUS = 3
    DM_COORD_MAP_SHELL = 4
    DM_COORD_MAP_SINUSOID = 5
    DM_COORD_MAP_UNKNOWN = 6
end 

@enum DMPlexCSRAlgorithm begin
    DM_PLEX_CSR_MAT = 0
    DM_PLEX_CSR_GRAPH = 1
    DM_PLEX_CSR_OVERLAP = 2
end 

