# EXCLUDE FROM TESTING
#=
  ex62b.jl — Stokes Problem on a Gmsh circle-in-box geometry.
  Derived from ex62.jl (Julia port of PETSc snes/tutorials/ex62.c).

  Solves  −∇·(2μ ε(u)) + ∇p = f   (momentum)
           ∇·u              = 0   (incompressibility)
  on a square domain Ω = (−1,1)² containing a circular inclusion.
  The mesh is generated by Gmsh with element boundaries conforming to
  the circle edge. For this first step the viscosity is uniform (same
  inside and outside the circle). Dirichlet BCs are applied on the
  outer box walls using the manufactured exact solutions from ex62.

  Mesh geometry (set via command-line options):
    -mesh_h VAL             element size (default 0.1)
    -mesh_h_inclusion VAL   element size at the inclusion boundary (default = mesh_h)
    -inclusion_R VAL  circle radius, centred at (0,0) (default 0.2)
    -vtk_output FILE  write solution to FILE.vtu (ParaView / VisIt)
    -exx_bg VAL       background x-extensional strain rate (default 0.0)
    -eyy_bg VAL       background y-extensional strain rate (default 0.0)
                      ezz_bg is always set to -(exx_bg+eyy_bg) to enforce ∇·u=0

  Discretisation (default: P2 velocity + P-1 discontinuous pressure):
    -vel_petscspace_degree  N   velocity polynomial degree (default 2)
    -pres_petscspace_degree N   pressure polynomial degree (default 1, discontinuous)

  Solution types (-sol):
    quadratic  — polynomial MMS, exact for P2 velocity  (default)
    trig       — trigonometric MMS, tests convergence rate
    bg         — background pure shear, BCs: Vx = x*exx_bg, Vy = y*eyy_bg, f = 0
    grav       — gravity-driven flow, no-slip walls, density contrast drives motion
                 (falling/rising cylinder in 2D, sphere in 3D)

  Quadratic MMS:
    2D: u = [x²+y², 2x²−2xy],  p = x+y−1,       f = (4μ−1) [1,1]
    3D: u = [2x²+y²+z², 2x²−2xy, 2x²−2xz],  p = x+y+z−3/2,
        f = [8μ−1, 4μ−1, 4μ−1]

  Trigonometric MMS:
    2D: u = [sin(πx)+sin(πy), −π cos(πx)y],  p = sin(2πx)+sin(2πy)
    3D: u = [2sin(πx)+sin(πy)+sin(πz), −π cos(πx)y, −π cos(πx)z],
        p = sin(2πx)+sin(2πy)+sin(2πz)

  Parameters:
    -mu val             background (matrix) dynamic shear viscosity (default 1.0)
    -mu_inclusion val   viscosity inside the circular inclusion (default = mu)
    -rho_bg val         background (matrix) density (default 1.0)
    -rho_inclusion val  density inside the inclusion (default = rho_bg)
    -gravity val        gravitational acceleration magnitude, pointing in −y (default 1.0)
    -exx_bg val         background x-extensional strain rate (default 0.0)
    -eyy_bg val         background y-extensional strain rate (default 0.0)
    -sol name           solution type: quadratic (default), trig, bg, or grav

  ── Solvers ───────────────────────────────────────────────────────────────────

  The Stokes system is a saddle-point problem; a block-structured Schur-
  complement fieldsplit preconditioner is used throughout.  Two options:

  (A) Direct solver — exact, suitable for 2D or small 3D problems:
    -pc_use_amat
    -pc_type fieldsplit -pc_fieldsplit_type schur
    -pc_fieldsplit_schur_factorization_type full
    -pc_fieldsplit_schur_precondition a11
    -fieldsplit_velocity_pc_type lu
    -fieldsplit_pressure_ksp_rtol 1e-9 -fieldsplit_pressure_pc_type lu
    -ksp_rtol 1e-9

  (B) Algebraic multigrid (GAMG) on velocity + Jacobi on pressure —
      recommended for 3D or large 2D; no mesh hierarchy needed:
    -pc_use_amat
    -pc_type fieldsplit -pc_fieldsplit_type schur
    -pc_fieldsplit_schur_factorization_type full
    -pc_fieldsplit_schur_precondition a11
    -fieldsplit_velocity_ksp_type cg
    -fieldsplit_velocity_pc_type gamg
    -fieldsplit_pressure_ksp_type preonly -fieldsplit_pressure_pc_type jacobi
    -ksp_type fgmres -ksp_rtol 1e-6
    -snes_rtol 1e-6

  (C) Geometric multigrid (GMG) on velocity — requires a mesh hierarchy built
      by PETSc uniformly refining the loaded Gmsh mesh N times via -dm_refine N.
      Use a coarser mesh_h so the coarse level is affordable, then refine up:
    -mesh_h 0.4                         # coarse level (3D default is 0.2)
    -dm_refine 2                        # 2 refinements → 3 levels total
    -pc_use_amat
    -pc_type fieldsplit -pc_fieldsplit_type schur
    -pc_fieldsplit_schur_factorization_type full
    -pc_fieldsplit_schur_precondition a11
    -fieldsplit_velocity_ksp_type fgmres
    -fieldsplit_velocity_pc_type mg
    -fieldsplit_velocity_mg_levels_ksp_type chebyshev
    -fieldsplit_velocity_mg_levels_pc_type sor
    -fieldsplit_velocity_mg_coarse_pc_type lu
    -fieldsplit_pressure_ksp_type preonly -fieldsplit_pressure_pc_type jacobi
    -ksp_type fgmres -ksp_rtol 1e-6
    -snes_rtol 1e-6

  Notes on solver choice:
    - With -pc_fieldsplit_schur_precondition a11 the velocity block approximates
      the Schur complement.  Works well for mild viscosity contrasts.
    - For strong viscosity contrasts (mu ratio > ~100) try
        -pc_fieldsplit_schur_precondition full
      with GAMG on both blocks, or switch to block-diagonal
        -pc_fieldsplit_type additive
    - GAMG (B) automatically detects near-null-space (rigid-body modes); GMG (C)
      relies on the smoother cascade — SOR or Chebyshev+Jacobi both work well.
    - GMG note: -dm_refine N builds a refinement hierarchy ONLY inside the MG
      preconditioner.  The SNES still assembles and solves on the Gmsh mesh
      (mesh_h), so the solution accuracy and VTK output are at mesh_h resolution.
      Use a smaller mesh_h for finer physical resolution; dm_refine only
      controls the number of MG levels, not the solution mesh.

  ── Run examples ─────────────────────────────────────────────────────────────

  2D background shear, direct solver:
    julia --project=examples examples/ex62b.jl \
          -sol bg -exx_bg 1.0 -eyy_bg -1.0 -mu_inclusion 0.1 \
          -pc_use_amat -pc_type fieldsplit -pc_fieldsplit_type schur \
          -pc_fieldsplit_schur_factorization_type full \
          -pc_fieldsplit_schur_precondition a11 \
          -fieldsplit_velocity_pc_type lu \
          -fieldsplit_pressure_ksp_rtol 1e-9 -fieldsplit_pressure_pc_type lu \
          -ksp_rtol 1e-9 -snes_rtol 1e-9 -vtk_output out.vtu

  3D background shear, GAMG iterative solver (ezz = -(exx+eyy) automatically):
    julia --project=examples examples/ex62b.jl \
          -dm_plex_dim 3 -sol bg -exx_bg 1.0 -eyy_bg -0.5 -mu_inclusion 0.01 \
          -pc_use_amat -pc_type fieldsplit -pc_fieldsplit_type schur \
          -pc_fieldsplit_schur_factorization_type full \
          -pc_fieldsplit_schur_precondition a11 \
          -fieldsplit_velocity_ksp_type cg -fieldsplit_velocity_pc_type gamg \
          -fieldsplit_pressure_ksp_type preonly -fieldsplit_pressure_pc_type jacobi \
          -ksp_type fgmres -ksp_rtol 1e-6 -snes_rtol 1e-6 -vtk_output out3d.vtu

  3D background shear, geometric multigrid (coarse mesh → 2 refinements):
    julia --project=examples examples/ex62b.jl \
          -dm_plex_dim 3 -sol bg -exx_bg 1.0 -eyy_bg -0.5 -mu_inclusion 0.01 \
          -mesh_h 0.4 -dm_refine 2 \
          -pc_use_amat -pc_type fieldsplit -pc_fieldsplit_type schur \
          -pc_fieldsplit_schur_factorization_type full \
          -pc_fieldsplit_schur_precondition a11 \
          -fieldsplit_velocity_ksp_type fgmres \
          -fieldsplit_velocity_pc_type mg \
          -fieldsplit_velocity_mg_levels_ksp_type chebyshev \
          -fieldsplit_velocity_mg_levels_pc_type sor \
          -fieldsplit_velocity_mg_coarse_pc_type lu \
          -fieldsplit_pressure_ksp_type preonly -fieldsplit_pressure_pc_type jacobi \
          -ksp_type fgmres -ksp_rtol 1e-6 -snes_rtol 1e-6 -vtk_output out3d_mg.vtu

  References:
    - PETSc 3.23  src/snes/tutorials/ex62.c
=#

# When included from the REPL with the main project active, Gmsh lives in the
# examples sub-environment.  Activate it automatically so `import Gmsh` works.
if isinteractive()
    import Pkg
    Pkg.activate(joinpath(@__DIR__))
end

using MPI
using PETSc
using PETSc: LibPETSc
import Gmsh: gmsh
using ForwardDiff

# ── REPL options (edit when running interactively) ───────────────────────────
# Used in place of ARGS when the script is loaded from the REPL.
const repl_opts = String[
    "-sol",                          "grav",
    "-mesh_h",                       "0.05",
    "-mesh_h_inclusion",             "0.02",
    "-rho_bg",                       "1.0",
    "-rho_inclusion",                "2.0",
    "-gravity",                      "1.0",
    "-mu_inclusion",                 "0.1",   # 10× softer inclusion
    # "-vel_petscspace_degree",      "2",
    # "-pres_petscspace_degree",     "1",
    "-pc_use_amat",
    "-pc_type",                      "fieldsplit",
    "-pc_fieldsplit_type",           "schur",
    "-pc_fieldsplit_schur_factorization_type", "full",
    "-pc_fieldsplit_schur_precondition",      "a11",
    "-fieldsplit_velocity_pc_type",  "lu",
    "-fieldsplit_pressure_ksp_rtol", "1e-9",
    "-fieldsplit_pressure_pc_type",  "lu",
    "-ksp_rtol",                     "1e-9",
    "-snes_rtol",                    "1e-9",
    "-snes_monitor",
    "-vtk_output",                   "ex62b_out.vtu",
]

# ── PETSc / MPI init ─────────────────────────────────────────────────────────
args     = isinteractive() ? repl_opts : collect(String, ARGS)
opts     = PETSc.parse_options(args)
petsclib = PETSc.getlib(; PetscScalar = Float64)
MPI.Initialized() || MPI.Init()
PETSc.initialize(petsclib)

@isdefined(PetscInt)    || const PetscInt    = petsclib.PetscInt
@isdefined(PetscScalar) || const PetscScalar = Float64
@isdefined(PetscReal)   || const PetscReal   = Float64

# Module-level globals for background strain rates — read by @cfunction-based BCs.
bg_exx = 0.0
bg_eyy = 0.0
bg_ezz = 0.0

comm = MPI.COMM_WORLD

# ── Option parsing ────────────────────────────────────────────────────────────
o           = NamedTuple(pairs(opts))
sol_type    = string(get(o, :sol, "quadratic"))
mu_val      = parse(Float64, string(get(o, :mu, "1.0")))
mu_inclusion = parse(Float64, string(something(get(o, :mu_inclusion, nothing), string(mu_val))))
dim_opt     = parse(Int,     string(get(o, Symbol("dm_plex_dim"), "2")))
default_h   = dim_opt == 3 ? "0.2" : "0.02"   # coarser default in 3D
mesh_h      = parse(Float64, string(get(o, :mesh_h, default_h)))
mesh_h_incl = parse(Float64, string(get(o, :mesh_h_inclusion, string(mesh_h))))
inclusion_R = parse(Float64, string(get(o, :inclusion_R, "0.2")))
vel_degree  = parse(Int,     string(get(o, Symbol("vel_petscspace_degree"),  "2")))
pres_degree = parse(Int,     string(get(o, Symbol("pres_petscspace_degree"), "1")))
exx_bg      = let i = findfirst(==("-exx_bg"), args); i !== nothing && i < length(args) ? parse(Float64, args[i+1]) : 0.0; end
eyy_bg      = let i = findfirst(==("-eyy_bg"), args); i !== nothing && i < length(args) ? parse(Float64, args[i+1]) : 0.0; end
ezz_bg      = -(exx_bg + eyy_bg)   # enforces ∇·u = exx + eyy + ezz = 0
rho_bg      = parse(Float64, string(get(o, :rho_bg,        "1.0")))
rho_inclusion = parse(Float64, string(something(get(o, :rho_inclusion, nothing), string(rho_bg))))
gravity     = parse(Float64, string(get(o, :gravity, "1.0")))
global bg_exx = exx_bg
global bg_eyy = eyy_bg
global bg_ezz = ezz_bg

@assert sol_type in ("quadratic", "trig", "bg", "grav") "-sol must be quadratic, trig, bg, or grav"

# ── Constitutive functions ────────────────────────────────────────────────────
#
# Auxiliary field layout (a): a[1] = phase (1=matrix, 2=inclusion) at this point.
# Constants layout (cst):     [1]=μ[1], [2]=μ[2], [3]=ρ[1], [4]=ρ[2], [5]=g_mag, [6]=R
#
# These are the only places the rheology appears — swap them to get a
# different constitutive law (e.g. power-law, viscoplastic).
#
# ε_{cd} = ½(∂u_c/∂x_d + ∂u_d/∂x_c)   (symmetric part of ∇u)
@inline function compute_strainrate!(eps, dim_, u_x)
    for c in 0:dim_-1, d in 0:dim_-1
        eps[c*dim_+d+1] = 0.5 * (u_x[c*dim_+d+1] + u_x[d*dim_+c+1])
    end
end

# Compute total stress σ = τ - p_eff I and return the effective pressure.
# For isoviscous incompressible flow: τ_{cd} = 2μ ε_{cd}, p_eff = p (unchanged).
# Future coupled rheologies (bulk viscosity, Drucker-Prager, etc.) modify p_eff here.
@inline function deviatoric_stress_pressure!(sigma, dim_, eps, mu, p)
    for c in 0:dim_-1, d in 0:dim_-1
        sigma[c*dim_+d+1] = 2 * mu * eps[c*dim_+d+1]
    end
    p_eff = p   # future: e.g. p - zeta * tr(eps) for bulk viscosity
    for c in 0:dim_-1
        sigma[c*dim_+c+1] -= p_eff
    end
    return p_eff
end

# ∂σ/∂(∂u/∂x) tangent via AD of deviatoric_stress_pressure! w.r.t. ε only.
# The strain-rate factor ∂ε_{gh}/∂(∂u_e/∂x_f) = ½(δ_{ge}δ_{hf} + δ_{gf}δ_{he})
# is known analytically, so we apply it as a column symmetrisation:
#   ∂σ_{ab}/∂(∂u_e/∂x_f) = ½( ∂σ_{ab}/∂ε_{ef} + ∂σ_{ab}/∂ε_{fe} )
# PETSc g3 layout: g3[((fc*dim+gc)*dim+df)*dim+dg + 1] = ∂σ_{fc,df}/∂(∂u_{gc}/∂x_{dg})
@inline function deviatoric_stress_tangent!(K, dim_, u_x, mu, p)
    n      = dim_ * dim_
    eps_v  = [real(u_x[i]) for i in 1:n]   # reuse buffer; values don't matter for AD seed
    compute_strainrate!(eps_v, dim_, [real(u_x[i]) for i in 1:n])
    # AD: differentiate σ w.r.t. ε
    J_eps = ForwardDiff.jacobian(eps_v) do e
        sigma_v = similar(e)
        deviatoric_stress_pressure!(sigma_v, dim_, e, mu, p)
        sigma_v
    end
    # Apply chain rule: symmetrise columns to account for ∂ε/∂(∇u)
    for i in 0:n-1, j in 0:n-1
        fc, df  = divrem(i, dim_)
        gc, dg  = divrem(j, dim_)
        j_sym   = dg * dim_ + gc          # index of transposed entry (fe swapped)
        dσ_dux  = 0.5 * (J_eps[i+1, j+1] + J_eps[i+1, j_sym+1])
        K[((fc*dim_+gc)*dim_+df)*dim_+dg + 1] += dσ_dux
    end
end

# ── Pointwise assembly: momentum flux f1_u ────────────────────────────────────
# Reuses f1 as a temporary buffer for ε (no allocation needed):
#   step 1: f1 ← ε   (strain rates)
#   step 2: f1 ← σ = τ − p_eff I   (via deviatoric_stress_pressure!)
function f1_u(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
              aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, f1)
    phase = Int(round(real(a[1])))
    mu    = real(cst[phase])
    p     = real(u[dim_+1])
    compute_strainrate!(f1, dim_, u_x)
    deviatoric_stress_pressure!(f1, dim_, f1, mu, p)
end
const f1_u_ptr = PETSc.@petsc_residual_fn(f1_u, dim_*dim_)

# Continuity: f0 = −∇·u
function f0_p(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
              aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, f0)
    f0[1] = 0.0
    for d in 0:dim_-1
        f0[1] -= u_x[d*dim_+d+1]
    end
end
const f0_p_ptr = PETSc.@petsc_residual_fn(f0_p, 1)

# ── Body-force functions (one per MMS solution type) ──────────────────────────
#
# Quadratic MMS body force:
#   2D: f = [1 − 4μ, 1 − 4μ]   (negated → added as rhs, sign convention)
#   3D: f = [1 − 8μ, 1 − 4μ, 1 − 4μ]
# Note: PETSc weak form sign: < v, f > on the RHS means f0 = −f_body
#   so f0[1] = (dim−1)*4μ − 1, f0[d≥2] = 4μ − 1
#
function f0_quadratic_u(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
                         aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, f0)
    mu = real(cst[1])
    f0[1] = (dim_ - 1) * 4mu - 1.0
    for d in 2:dim_
        f0[d] = 4mu - 1.0
    end
end
const f0_quadratic_u_ptr = PETSc.@petsc_residual_fn(f0_quadratic_u, dim_)

# Trigonometric MMS body force:
#   f_x = 2π cos(2πx) + μ(dim−1)π² sin(πx) + μπ² Σ_{d>0} sin(πx_d)
#   f_d = 2π cos(2πx_d) − μπ³ cos(πx) x_d   for d > 0
#
function f0_trig_u(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
                   aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, f0)
    mu = real(cst[1])
    f0[1] = -2π*cos(2π*x[1]) - (dim_-1)*mu*π^2*sin(π*x[1])
    for d in 2:dim_
        f0[1] -= mu*π^2*sin(π*x[d])
        f0[d]  = -2π*cos(2π*x[d]) + mu*π^3*cos(π*x[1])*x[d]
    end
end
const f0_trig_u_ptr = PETSc.@petsc_residual_fn(f0_trig_u, dim_)

# Zero body force for background deformation mode (no MMS forcing)
function f0_zero_u(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
                   aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, f0)
    for d in 1:dim_; f0[d] = 0.0; end
end
const f0_zero_u_ptr = PETSc.@petsc_residual_fn(f0_zero_u, dim_)

# Gravity body force: f_body = ρ g (−ŷ direction).
# In PETSc weak-form sign convention, f0 = −f_body, so:
#   f0[last] = ρ * g_mag   (positive component drives downward motion)
function f0_grav_u(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
                   aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, f0)
    phase = Int(round(real(a[1])))
    rho   = real(cst[2 + phase])   # cst[3]=ρ[1], cst[4]=ρ[2]
    g     = real(cst[5])
    for d in 1:dim_; f0[d] = 0.0; end
    f0[dim_] = rho * g
end
const f0_grav_u_ptr = PETSc.@petsc_residual_fn(f0_grav_u, dim_)

# ── Jacobians ─────────────────────────────────────────────────────────────────

# J_uu (g3): tangent of deviatoric stress w.r.t. ∇u, computed by AD
function g3_uu(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
               aOff, aOff_x, a, a_t, a_x, t, utShift, x, nC, cst, g3)
    phase = Int(round(real(a[1])))
    mu    = real(cst[phase])
    p     = real(u[dim_+1])
    deviatoric_stress_tangent!(g3, dim_, u_x, mu, p)
end
const g3_uu_ptr = PETSc.@petsc_jacobian_fn(g3_uu, dim_*dim_*dim_*dim_)

# J_up (g2): ∂σ_{fc,df}/∂p via AD of deviatoric_stress_pressure! w.r.t. p.
# Layout: g2[fc*dim+df + 1] = ∂σ_{fc,df}/∂p.
# For isoviscous: -δ_{fc,df}.  For coupled rheologies (e.g. viscoplastic where
# p_eff depends on p) the AD picks up the extra terms automatically.
function g2_up(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
               aOff, aOff_x, a, a_t, a_x, t, utShift, x, nC, cst, g2)
    phase   = Int(round(real(a[1])))
    mu      = real(cst[phase])
    p       = real(u[dim_+1])
    n       = dim_ * dim_
    eps_cur = [0.0 for _ in 1:n]
    compute_strainrate!(eps_cur, dim_, [real(u_x[i]) for i in 1:n])
    # ForwardDiff.derivative: scalar input p → vector output σ
    dσ_dp = ForwardDiff.derivative(Float64(p)) do p_val
        sv = zeros(typeof(p_val), n)
        deviatoric_stress_pressure!(sv, dim_, eps_cur, mu, p_val)
        sv
    end
    for i in 1:n; g2[i] = dσ_dp[i]; end
end
const g2_up_ptr = PETSc.@petsc_jacobian_fn(g2_up, dim_*dim_)

# J_pu (g1): ⟨q, −∇·u⟩ — kinematic incompressibility, independent of rheology.
function g1_pu(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
               aOff, aOff_x, a, a_t, a_x, t, utShift, x, nC, cst, g1)
    for d in 0:dim_-1; g1[d*dim_+d+1] = -1.0; end
end
const g1_pu_ptr = PETSc.@petsc_jacobian_fn(g1_pu, dim_*dim_)

# J_pp preconditioner (g0): (1/μ)⟨q, p⟩
function g0_pp(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
               aOff, aOff_x, a, a_t, a_x, t, utShift, x, nC, cst, g0)
    g0[1] = 1.0 / real(cst[Int(round(real(a[1])))])
end
const g0_pp_ptr = PETSc.@petsc_jacobian_fn(g0_pp, 1)

# ── VTK post-processing: strain rate tensor ─────────────────────────────────
#
# Strain rate ε_{cd} = ½(∂u_c/∂x_d + ∂u_d/∂x_c), stored as a 3×3 row-major
# output (9 components, zero-padded in 2D) to match ex17 convention.
# u_x layout (0-based): u_x[c*dim+d+1] = ∂u_c/∂x_d
function compute_strainrate_3x3(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
                                aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, out)
    for i in 1:9; out[i] = 0.0; end
    for c in 0:dim_-1, d in 0:dim_-1
        out[c*3+d+1] = 0.5*(u_x[c*dim_+d+1] + u_x[d*dim_+c+1])
    end
end
const compute_strainrate_3x3_ptr = PETSc.@petsc_residual_fn(compute_strainrate_3x3, 9)

# VTK copy kernels: extract velocity (field 0) and pressure (field 1) from the
# combined solution vector.  Must be at top-level scope for @cfunction.
function copy_vel(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
                  aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, out_)
    for c in 1:dim_; out_[c] = u[c]; end
end
const copy_vel_ptr = PETSc.@petsc_residual_fn(copy_vel, dim_)

function copy_pres(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
                   aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, out_)
    out_[1] = u[dim_+1]
end
const copy_pres_ptr = PETSc.@petsc_residual_fn(copy_pres, 1)

# VTK kernels use position + cst[6]=R (geometry-based, no auxiliary field needed).
# cst layout: [mu[1], mu[2], rho[1], rho[2], g, R]
function copy_mu(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
                 aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, out_)
    out_[1] = real(sum(x[i]^2 for i in 1:dim_) < cst[6]^2 ? cst[2] : cst[1])
end
const copy_mu_ptr = PETSc.@petsc_residual_fn(copy_mu, 1)

function copy_phase(dim_, Nf, NfAux, uOff, uOff_x, u, u_t, u_x,
                    aOff, aOff_x, a, a_t, a_x, t, x, nC, cst, out_)
    out_[1] = sum(x[i]^2 for i in 1:dim_) < cst[6]^2 ? 2.0 : 1.0
end
const copy_phase_ptr = PETSc.@petsc_residual_fn(copy_phase, 1)

# ── Exact solutions ───────────────────────────────────────────────────────────
#
# Quadratic MMS:
#   2D: u=[x²+y², 2x²−2xy],  p=x+y−1
#   3D: u=[2x²+y²+z², 2x²−2xy, 2x²−2xz],  p=x+y+z−3/2
#
function quadratic_vel(t, x, u, ctx)
    dim = length(x)
    u[1] = (dim - 1) * x[1]^2
    for c in 2:dim
        u[1] += x[c]^2
        u[c]  = 2*x[1]^2 - 2*x[1]*x[c]
    end
end
const quadratic_vel_ptr = PETSc.@petsc_simple_fn(quadratic_vel)

function quadratic_pres(t, x, u, ctx)
    u[1] = sum(x) - 0.5*length(x)
end
const quadratic_pres_ptr = PETSc.@petsc_simple_fn(quadratic_pres)

#
# Trigonometric MMS:
#   2D: u=[sin(πx)+sin(πy), −π cos(πx)y],  p=sin(2πx)+sin(2πy)
#   3D: u=[2sin(πx)+sin(πy)+sin(πz), −π cos(πx)y, −π cos(πx)z],
#       p=sin(2πx)+sin(2πy)+sin(2πz)
#
function trig_vel(t, x, u, ctx)
    dim = length(x)
    u[1] = (dim - 1) * sin(π*x[1])
    for c in 2:dim
        u[1] += sin(π*x[c])
        u[c]  = -π*cos(π*x[1])*x[c]
    end
end
const trig_vel_ptr = PETSc.@petsc_simple_fn(trig_vel)

function trig_pres(t, x, u, ctx)
    u[1] = sum(sin(2π*xi) for xi in x)
end
const trig_pres_ptr = PETSc.@petsc_simple_fn(trig_pres)

# Helper functions for the pressure null space constructor
function zero_vel(t, x, u, ctx)
    for c in 1:length(u); u[c] = 0.0; end
end
const zero_vel_ptr = PETSc.@petsc_simple_fn(zero_vel)

function one_pres(t, x, u, ctx)
    u[1] = 1.0
end
const one_pres_ptr = PETSc.@petsc_simple_fn(one_pres)

# Background deformation BC: Vx = x*exx_bg, Vy = y*eyy_bg, Vz = z*ezz_bg.
# ezz_bg defaults to -(exx_bg+eyy_bg) to satisfy incompressibility.
function bg_vel(t, x, u, ctx)
    u[1] = x[1] * bg_exx
    u[2] = x[2] * bg_eyy
    length(u) >= 3 && (u[3] = x[3] * bg_ezz)
end
const bg_vel_ptr = PETSc.@petsc_simple_fn(bg_vel)

# ── Select exact solution functions based on sol_type ─────────────────────────
# Phase field: 1 = matrix, 2 = inclusion.  Reads global inclusion_R.
function phase_fn(t, x, u, ctx)
    u[1] = sum(xi^2 for xi in x) < inclusion_R^2 ? 2.0 : 1.0
end
const phase_fn_ptr = PETSc.@petsc_simple_fn(phase_fn)

exact_vel_ptr  = sol_type == "quadratic" ? quadratic_vel_ptr  :
                 sol_type == "trig"      ? trig_vel_ptr        :
                 sol_type == "bg"        ? bg_vel_ptr          : zero_vel_ptr
exact_pres_ptr = sol_type == "quadratic" ? quadratic_pres_ptr :
                 sol_type == "trig"      ? trig_pres_ptr       : quadratic_pres_ptr

# ── Pressure null space constructor ───────────────────────────────────────────
function pressure_nsp_constructor(
    dm_ptr::Ptr{Cvoid}, ::PetscInt, ::PetscInt,
    nsp_pp::Ptr{LibPETSc.MatNullSpace},
)::PetscInt
    PL   = typeof(petsclib)
    dm_w = LibPETSc.PetscDM{PL}(dm_ptr)
    nvec = PETSc.DMGlobalVec(dm_w)
    PETSc.dm_project_function!(petsclib, dm_w, 0.0,
        [zero_vel_ptr, one_pres_ptr], nothing, LibPETSc.INSERT_ALL_VALUES, nvec)
    LibPETSc.VecNormalize(petsclib, nvec)
    GC.@preserve nvec begin
        nsp = PETSc.mat_null_space_create(petsclib, MPI.COMM_WORLD, (nvec,))
        unsafe_store!(nsp_pp, nsp)
    end
    PETSc.destroy(nvec)
    return PetscInt(0)
end
const pressure_nsp_ptr = Base.@cfunction(pressure_nsp_constructor, PetscInt,
    (Ptr{Cvoid}, PetscInt, PetscInt, Ptr{LibPETSc.MatNullSpace}))

# ── Gmsh mesh generation ─────────────────────────────────────────────────────
"""
Generate a Gmsh mesh of a [-1,1]^dim box with a spherical/circular inclusion.

Physical groups written to the .msh file:
  dim-D group 1 → "matrix"    (domain outside the inclusion)
  dim-D group 2 → "inclusion" (domain inside the inclusion)
  (dim-1)-D group 3 → "boundary" (outer box faces — Dirichlet BC support)

`h_incl` controls the element size on the inclusion surface; defaults to `h`.
"""
function generate_inclusion_mesh(
    filename::String;
    dim::Int        = 2,
    h::Float64      = 0.02,
    h_incl::Float64 = h,
    cx::Float64     = 0.0,
    cy::Float64     = 0.0,
    cz::Float64     = 0.0,
    R::Float64      = 0.2,
)
    gmsh.initialize()
    gmsh.option.setNumber("General.Terminal", 0)
    gmsh.model.add("inclusion_$(dim)d")

    if dim == 2
        outer = gmsh.model.occ.addRectangle(-1.0, -1.0, 0.0, 2.0, 2.0)
        incl  = gmsh.model.occ.addDisk(cx, cy, 0.0, R, R)
        gmsh.model.occ.fragment([(2, outer)], [(2, incl)])
        gmsh.model.occ.synchronize()

        ents   = gmsh.model.getEntities(2)
        masses = sort([(gmsh.model.occ.getMass(2, t), t) for (_, t) in ents])
        gmsh.model.addPhysicalGroup(2, [masses[2][2]], 1, "matrix")
        gmsh.model.addPhysicalGroup(2, [masses[1][2]], 2, "inclusion")

        outer_ents = [t for (d, t) in gmsh.model.getEntities(1)
                      if length(gmsh.model.getAdjacencies(d, t)[1]) == 1]
        gmsh.model.addPhysicalGroup(1, outer_ents, 3, "boundary")

        incl_ents = [t for (d, t) in gmsh.model.getEntities(1)
                     if length(gmsh.model.getAdjacencies(d, t)[1]) == 2]
        incl_pts  = gmsh.model.getBoundary([(1, c) for c in incl_ents],
                                            false, false, false)
    else  # dim == 3
        outer = gmsh.model.occ.addBox(-1.0, -1.0, -1.0, 2.0, 2.0, 2.0)
        incl  = gmsh.model.occ.addSphere(cx, cy, cz, R)
        gmsh.model.occ.fragment([(3, outer)], [(3, incl)])
        gmsh.model.occ.synchronize()

        ents   = gmsh.model.getEntities(3)
        masses = sort([(gmsh.model.occ.getMass(3, t), t) for (_, t) in ents])
        gmsh.model.addPhysicalGroup(3, [masses[2][2]], 1, "matrix")
        gmsh.model.addPhysicalGroup(3, [masses[1][2]], 2, "inclusion")

        outer_ents = [t for (d, t) in gmsh.model.getEntities(2)
                      if length(gmsh.model.getAdjacencies(d, t)[1]) == 1]
        gmsh.model.addPhysicalGroup(2, outer_ents, 3, "boundary")

        incl_ents = [t for (d, t) in gmsh.model.getEntities(2)
                     if length(gmsh.model.getAdjacencies(d, t)[1]) == 2]
        incl_pts  = gmsh.model.getBoundary([(2, s) for s in incl_ents],
                                            false, false, false)
    end

    gmsh.model.mesh.setSize(gmsh.model.getEntities(0), h)
    h_incl != h && gmsh.model.mesh.setSize(incl_pts, h_incl)

    gmsh.model.mesh.generate(dim)
    gmsh.write(filename)
    gmsh.finalize()
    return filename
end

# ── Mesh ──────────────────────────────────────────────────────────────────────
# Generate Gmsh mesh (2D: circle in square; 3D: sphere in cube) and load into PETSc.
# The outer box boundary is Physical Group 3 → PETSc "Face Sets" label value 3.
mshfile = tempname() * ".msh"
generate_inclusion_mesh(mshfile; dim = dim_opt, h = mesh_h, h_incl = mesh_h_incl,
                        cx = 0.0, cy = 0.0, cz = 0.0, R = inclusion_R)
dm = PETSc.DMPlex(petsclib, comm; dm_plex_filename = mshfile)

# ── Discretisation ────────────────────────────────────────────────────────────
dim     = LibPETSc.DMGetDimension(petsclib, dm)
simplex = PETSc.isplexsimplex(dm)

fe_vel  = PETSc.fe_create_default(petsclib, MPI.COMM_SELF, dim, dim, simplex;
                                   degree = vel_degree, prefix = "vel_")
LibPETSc.PetscObjectSetName(petsclib, convert(Ptr{Cvoid}, fe_vel), "velocity")

# Pressure: discontinuous P_k (P-1 by default) — inject the continuity=false
# option before creating the FE so PetscFECreateDefault picks it up.
let opts_disc = PETSc.Options(petsclib; pres_petscdualspace_lagrange_continuity = 0)
    push!(opts_disc)
    global fe_pres = PETSc.fe_create_default(petsclib, MPI.COMM_SELF, dim, 1, simplex;
                                             degree = pres_degree, prefix = "pres_")
    pop!(opts_disc)
end
LibPETSc.PetscObjectSetName(petsclib, convert(Ptr{Cvoid}, fe_pres), "pressure")

# Copy quadrature from velocity to pressure for consistent integration
PETSc.fe_copy_quadrature!(petsclib, fe_vel, fe_pres)

PETSc.setfield!(dm, 0, fe_vel)
PETSc.setfield!(dm, 1, fe_pres)
PETSc.createds!(dm)

# ── PetscDS setup ─────────────────────────────────────────────────────────────
ds = PETSc.getds(dm)

# constants: [mu[1], mu[2], rho[1], rho[2], g, R]
# Solve kernels index by phase from aux field; VTK kernels use R (cst[6]) geometrically.
PETSc.set_constants!(ds, [mu_val, mu_inclusion, rho_bg, rho_inclusion, gravity, inclusion_R])

if sol_type == "quadratic"
    PETSc.set_residual!(ds, 0, f0_quadratic_u_ptr, f1_u_ptr)
elseif sol_type == "trig"
    PETSc.set_residual!(ds, 0, f0_trig_u_ptr, f1_u_ptr)
elseif sol_type == "grav"
    PETSc.set_residual!(ds, 0, f0_grav_u_ptr, f1_u_ptr)
else  # "bg"
    PETSc.set_residual!(ds, 0, f0_zero_u_ptr, f1_u_ptr)
end
PETSc.set_residual!(ds, 1, f0_p_ptr, C_NULL)

PETSc.set_jacobian!(ds, 0, 0, C_NULL, C_NULL, C_NULL, g3_uu_ptr)
PETSc.set_jacobian!(ds, 0, 1, C_NULL, C_NULL, g2_up_ptr, C_NULL)
PETSc.set_jacobian!(ds, 1, 0, C_NULL, g1_pu_ptr, C_NULL, C_NULL)
PETSc.set_jacobian_preconditioner!(ds, 0, 0, C_NULL, C_NULL, C_NULL, g3_uu_ptr)
PETSc.set_jacobian_preconditioner!(ds, 1, 1, g0_pp_ptr, C_NULL, C_NULL, C_NULL)

PETSc.set_exact_solution!(ds, 0, exact_vel_ptr)
PETSc.set_exact_solution!(ds, 1, exact_pres_ptr)

# ── Auxiliary phase field (DG-P0, one value per cell) ────────────────────────
# phase_fn projects 1 (matrix) or 2 (inclusion) into each cell.
# The aux vec is attached to dm so residual/Jacobian kernels can read a[1].
dm_aux = PETSc.dmclone(dm)
fe_phase_aux = let opts = PETSc.Options(petsclib; phaseaux_petscdualspace_lagrange_continuity = 0)
    push!(opts)
    fe = PETSc.fe_create_default(petsclib, MPI.COMM_SELF, dim, 1, simplex;
                                  degree = 0, prefix = "phaseaux_")
    pop!(opts)
    fe
end
LibPETSc.PetscObjectSetName(petsclib, convert(Ptr{Cvoid}, fe_phase_aux), "phase")
PETSc.fe_copy_quadrature!(petsclib, fe_vel, fe_phase_aux)  # match primary DM quadrature
PETSc.setfield!(dm_aux, 0, fe_phase_aux)
PETSc.createds!(dm_aux)
aux_vec = PETSc.DMGlobalVec(dm_aux)
PETSc.dm_project_function!(petsclib, dm_aux, 0.0,
    [phase_fn_ptr], nothing, LibPETSc.INSERT_ALL_VALUES, aux_vec)
LibPETSc.DMSetAuxiliaryVec(petsclib, dm,
    LibPETSc.DMLabel(C_NULL), PetscInt(0), PetscInt(0), aux_vec)

# ── Boundary condition: Dirichlet on outer box walls ─────────────────────────
# Gmsh physical group 3 ("boundary") → PETSc "Face Sets" label, value 3.
# All velocity components are constrained; pressure is free.
label = PETSc.getlabel(dm, "Face Sets")
PETSc.add_boundary!(petsclib, dm, LibPETSc.DM_BC_ESSENTIAL, "wall", label,
                    PetscInt[3], 0, PetscInt[], exact_vel_ptr)

# ── Propagate discretisation and null space constructor to coarser levels ─────
let cdm = dm
    while convert(Ptr{Cvoid}, cdm) != C_NULL
        PETSc.dm_copy_disc!(dm, cdm)
        LibPETSc.DMSetNullSpaceConstructor(petsclib, cdm, PetscInt(1), pressure_nsp_ptr)
        cdm = PETSc.dm_get_coarse(cdm)
    end
end

# Attach constant null space to the pressure FE for the fieldsplit preconditioner
PETSc.fe_compose_constant_null_space!(petsclib, comm, fe_pres)

# ── Pressure null space (normalized constant-pressure mode) ───────────────────
null_vec = PETSc.DMGlobalVec(dm)
PETSc.dm_project_function!(petsclib, dm, 0.0,
    [zero_vel_ptr, one_pres_ptr], nothing, LibPETSc.INSERT_ALL_VALUES, null_vec)
LibPETSc.VecNormalize(petsclib, null_vec)
nullspace = GC.@preserve null_vec PETSc.mat_null_space_create(petsclib, comm, (null_vec,))

# ── SNES + solve ─────────────────────────────────────────────────────────────
snes = PETSc.SNES(petsclib, comm; opts...)
PETSc.setDM!(snes, dm)
u = PETSc.DMGlobalVec(dm)
PETSc.plex_set_snes_local_fem!(petsclib, dm)

has_opts = !isnothing(snes.opts)
has_opts && push!(snes.opts)
try
    LibPETSc.SNESSetFromOptions(petsclib, snes)
    LibPETSc.SNESSetUp(petsclib, snes)
    PETSc.snes_set_jacobian_null_space!(snes, nullspace)
    LibPETSc.SNESSolve(petsclib, snes, C_NULL, u)
finally
    has_opts && pop!(snes.opts)
end

if MPI.Comm_rank(comm) == 0
    its = LibPETSc.SNESGetIterationNumber(petsclib, snes)
    println("SNES converged in $its Newton iteration(s).")
end

# ── L² errors ────────────────────────────────────────────────────────────────
if sol_type != "bg" && sol_type != "grav"
    l2err = PETSc.dm_compute_l2diff(petsclib, dm, 0.0,
        [exact_vel_ptr, exact_pres_ptr], nothing, u)
    if MPI.Comm_rank(comm) == 0
        println("L2 error: $l2err")
    end
end

# ── VTK output ────────────────────────────────────────────────────────────────
# Write solution to VTK if -vtk_output <filename.vtu> is given.
# The output is always on the Gmsh mesh (controlled by mesh_h).  When using
# -dm_refine N for geometric multigrid, the refinement hierarchy lives only
# inside the MG preconditioner; the SNES assembles and solves on the original
# mesh, so finer VTK output requires a smaller mesh_h, not dm_refine.
# Produces three named fields:
#   "velocity"       — dim-component vector
#   "pressure"       — scalar
#   "strainrate"     — 3×3 tensor (9-component, row-major, zero-padded in 2D)
let vtk = get(o, :vtk_output, nothing)
    if vtk !== nothing
        fname = string(vtk)

        dm_out = PETSc.dmclone(dm)

        fe_out_vel = PETSc.fe_create_default(petsclib, MPI.COMM_SELF,
                         dim, dim, simplex; degree = vel_degree, prefix = "vel_")
        LibPETSc.PetscObjectSetName(petsclib, convert(Ptr{Cvoid}, fe_out_vel), "velocity")

        fe_out_pres = let opts_disc = PETSc.Options(petsclib; pres_petscdualspace_lagrange_continuity = 0)
            push!(opts_disc)
            fe = PETSc.fe_create_default(petsclib, MPI.COMM_SELF,
                      dim, 1, simplex; degree = pres_degree, prefix = "pres_")
            pop!(opts_disc)
            fe
        end
        LibPETSc.PetscObjectSetName(petsclib, convert(Ptr{Cvoid}, fe_out_pres), "pressure")

        fe_out_sr = PETSc.fe_create_default(petsclib, MPI.COMM_SELF,
                        dim, 9, simplex; prefix = "sr_")
        LibPETSc.PetscObjectSetName(petsclib, convert(Ptr{Cvoid}, fe_out_sr), "strainrate")

        # DG-P0 (degree 0, discontinuous) → one DOF per cell → VTK CellData
        make_dg0 = (prefix, name) -> let opts = PETSc.Options(petsclib;
                                              Symbol(prefix * "petscdualspace_lagrange_continuity") => 0)
            push!(opts)
            fe = PETSc.fe_create_default(petsclib, MPI.COMM_SELF,
                      dim, 1, simplex; degree = 0, prefix = prefix)
            pop!(opts)
            LibPETSc.PetscObjectSetName(petsclib, convert(Ptr{Cvoid}, fe), name)
            fe
        end

        fe_out_mu    = make_dg0("mu_",    "viscosity")
        fe_out_phase = make_dg0("phase_", "phase")

        PETSc.setfield!(dm_out, 0, fe_out_vel)
        PETSc.setfield!(dm_out, 1, fe_out_pres)
        PETSc.setfield!(dm_out, 2, fe_out_sr)
        PETSc.setfield!(dm_out, 3, fe_out_mu)
        PETSc.setfield!(dm_out, 4, fe_out_phase)
        PETSc.createds!(dm_out)

        out_vec = PETSc.dm_create_global_vec(dm_out)
        PETSc.petsc_setname!(petsclib, out_vec, "")

        PETSc.dm_project_field!(petsclib, dm_out, 0.0, u,
            [copy_vel_ptr, copy_pres_ptr, compute_strainrate_3x3_ptr,
             copy_mu_ptr, copy_phase_ptr],
            LibPETSc.INSERT_ALL_VALUES, out_vec)

        PETSc.vtk_save!(petsclib, comm, fname, out_vec)

        MPI.Comm_rank(comm) == 0 && PETSc.vtk_merge_tensor!(fname, "strainrate")

        MPI.Comm_rank(comm) == 0 &&
            println("Velocity, pressure, strain rate, viscosity and phase written to $fname")
    end
end

# ── Cleanup ───────────────────────────────────────────────────────────────────
GC.gc(true)
MPI.Barrier(comm)
PETSc.mat_null_space_destroy!(petsclib, nullspace)
PETSc.destroy(snes)
PETSc.destroy(u)
PETSc.destroy(null_vec)
PETSc.destroy(aux_vec)
PETSc.destroy(dm_aux)
PETSc.destroy(dm)

if !isinteractive()
    flush(stdout); flush(stderr)
    PETSc.finalize(petsclib)
    MPI.Barrier(comm)
    MPI.Finalize()
    ccall(:quick_exit, Cvoid, (Cint,), 0)
end
