# Generate everything that has to agree with the rename register.
#
#   julia --project=. scripts/generate_renames.jl
#
# Reads scripts/renames.jl and writes
#
#   src/deprecations.jl        forwarding shims (§17)
#   src/public_names.jl        the `public` declaration (§13.1)
#   src/audit_names.jl         the name sets src/audit.jl matches against
#   test/test_deprecations.jl  one test per shim (§17.3)
#
# None of those four files is edited by hand.

include(joinpath(@__DIR__, "renames.jl"))

const ROOT = normpath(joinpath(@__DIR__, ".."))

const HEADER = """
# This file is generated by scripts/generate_renames.jl from scripts/renames.jl.
# Do not edit it: edit the register and regenerate.
"""

ismacro(s::Symbol) = startswith(String(s), "@")

# ---------------------------------------------------------------------------
# Consistency checks
# ---------------------------------------------------------------------------

function check_register()
    olds = first.(RENAMES)
    length(unique(olds)) == length(olds) ||
        error("duplicate old name in RENAMES: $(filter(n -> count(==(n), olds) > 1, unique(olds)))")
    news = Set(last.(RENAMES))
    for n in news
        n in INTERNAL &&
            error("$n is both a rename target and internal")
    end
    for n in UNCHANGED_PUBLIC
        n in olds && error("$n is both unchanged and renamed")
        n in INTERNAL && error("$n is both unchanged-public and internal")
    end
    for (old, _) in CUSTOM_SHIMS
        old in olds || error("CUSTOM_SHIMS has $old, which is not in RENAMES")
    end
    for old in TYPE_RENAMES
        old in olds || error("TYPE_RENAMES has $old, which is not in RENAMES")
    end
    return nothing
end

# The `public` list: every new name plus every unchanged public name, minus the
# ones Base owns and the ones that are exported (a name cannot be both).
function public_names()
    names = Symbol[]
    for (_, new) in RENAMES
        new in BASE_TARGETS && continue
        push!(names, new)
    end
    append!(names, UNCHANGED_PUBLIC)
    exported = Set(EXPORTED)
    return sort!(unique!(filter(n -> !(n in exported), names)); by = String)
end

# ---------------------------------------------------------------------------
# src/deprecations.jl
# ---------------------------------------------------------------------------

function write_deprecations(path)
    io = IOBuffer()
    print(io, HEADER)
    print(
        io,
        """
#
# Deprecation shims for the v0.5 rename (docs/src/man/naming.md §17). They are
# removed in v0.6.
#
# `Base.@deprecate` is not used: it calls `Base.depwarn`, which prints nothing
# unless Julia was started with `--depwarn=yes`, and a migration window that
# prints nothing is not a migration window (§17.1).

\"\"\"
    @renamed old new

Define `old` as a deprecated spelling of `new`.

The generated method forwards every argument and keyword argument, and warns once
per call site. The warning goes through `@warn` rather than `Base.depwarn`, so it
is printed whatever `--depwarn` is set to.
\"\"\"
macro renamed(old, new)
    msg = "\$old is deprecated, use \$new"
    return quote
        function \$(esc(old))(args...; kwargs...)
            @warn \$msg maxlog = 1
            return \$(esc(new))(args...; kwargs...)
        end
    end
end

""",
    )

    print(io, "# Renamed functions\n\n")
    for (old, new) in RENAMES
        old in TYPE_RENAMES && continue
        ismacro(old) && continue
        if haskey(CUSTOM_SHIMS, old)
            print(io, strip(CUSTOM_SHIMS[old]), "\n\n")
        else
            println(io, "@renamed $old $new")
        end
    end

    print(io, "\n# Renamed macros\n\n")
    for (old, new) in RENAMES
        ismacro(old) || continue
        println(
            io,
            """
            macro $(String(old)[2:end])(args...)
                @warn "$old is deprecated, use $new" maxlog = 1
                return Expr(:macrocall, GlobalRef(@__MODULE__, Symbol("$new")), __source__, args...)
            end
            """,
        )
    end

    print(io, "\n# Renamed types: a `const` alias, so `isa` and dispatch keep working\n\n")
    for (old, new) in RENAMES
        old in TYPE_RENAMES || continue
        if old in TYPE_RENAMES_INSOURCE
            println(io, "# `$old` is aliased where `$new` is defined.")
        else
            println(io, "const $old = $new")
        end
    end

    write(path, String(take!(io)))
    return nothing
end

# ---------------------------------------------------------------------------
# src/public_names.jl
# ---------------------------------------------------------------------------

function write_public(path)
    io = IOBuffer()
    print(io, HEADER)
    print(
        io,
        """
#
# The high-level API that is not exported (docs/src/man/naming.md §13.1).
# Julia 1.12 is the minimum supported version, so this is unconditional.

""",
    )
    names = public_names()
    # `public` takes a comma-separated list; wrap it so the file stays readable.
    line = "public "
    for (i, n) in enumerate(names)
        item = String(n) * (i == length(names) ? "" : ",")
        if length(line) + length(item) + 1 > 92
            println(io, rstrip(line))
            line = "       "
        end
        line *= (endswith(line, " ") ? "" : " ") * item
    end
    println(io, rstrip(line))
    write(path, String(take!(io)))
    return nothing
end

# ---------------------------------------------------------------------------
# src/audit_names.jl
# ---------------------------------------------------------------------------

function write_audit_names(path)
    io = IOBuffer()
    print(io, HEADER)
    print(
        io,
        """
#
# The names src/audit.jl matches against. Generated so that the next rename
# cannot blind the auditor: after a rename its patterns would otherwise stop
# matching and it would report no leaks on leaking code.

\"\"\"
    AUDIT_TYPE_CREATORS

Type constructors whose name is also the kind of object they create.
\"\"\"
""",
    )
    println(io, "const AUDIT_TYPE_CREATORS = Dict{Symbol, String}(")
    for k in sort!(collect(keys(AUDIT_TYPE_CREATORS)); by = String)
        println(io, "    :$k => $(repr(AUDIT_TYPE_CREATORS[k])),")
    end
    println(io, ")\n")

    print(
        io,
        """
\"\"\"
    AUDIT_NAMED_CREATORS

Creators whose name carries no `Create`/`Duplicate` marker for
[`audit_creator`](@ref) to recognise by shape.
\"\"\"
""",
    )
    println(io, "const AUDIT_NAMED_CREATORS = Dict{Symbol, String}(")
    for k in sort!(collect(keys(AUDIT_NAMED_CREATORS)); by = String)
        println(io, "    :$k => $(repr(AUDIT_NAMED_CREATORS[k])),")
    end
    println(io, ")\n")

    print(
        io,
        """
\"\"\"
    AUDIT_DESTROYER_NAMES

Names that release a PETSc object. `finalizer` counts: it hands the release to
the garbage collector rather than performing it, but the object is accounted for.
\"\"\"
""",
    )
    println(
        io,
        "const AUDIT_DESTROYER_NAMES = Set{Symbol}([" *
        join((":$n" for n in AUDIT_DESTROYERS), ", ") *
        "])",
    )
    write(path, String(take!(io)))
    return nothing
end

# ---------------------------------------------------------------------------
# test/test_deprecations.jl
# ---------------------------------------------------------------------------

function write_tests(path)
    io = IOBuffer()
    print(io, HEADER)
    print(
        io,
        """
#
# One test per shim (docs/src/man/naming.md §17.3). This is the only file in the
# suite that calls the v0.4 names; everything else is on the v0.5 API.
#
# A forwarding shim warns before it forwards, so calling it with an argument the
# replacement cannot accept still proves that the shim exists, warns, and hands
# the call on. `Probe` is that argument.

using Test
using PETSc

struct DeprecationProbe end

# `@petsc_*_fn` read `PetscInt`/`PetscReal`/`PetscScalar` out of the calling module,
# so the expansion needs a module that has them.
module DeprecationMacroEnv
using PETSc
const PetscInt = Int64
const PetscReal = Float64
const PetscScalar = Float64
probe_simple(t, x, u, ctx) = nothing
probe_point(args...) = nothing
const Nf = 1
end

warns(f) = @test_logs (:warn, r"deprecated") match_mode = :any f()

# Call a shim in a way that reaches the warning but cannot go wrong afterwards.
function probe_shim(name::Symbol)
    f = getproperty(PETSc, name)
    warns() do
        try
            f(DeprecationProbe())
        catch
            # A MethodError from the replacement is the expected outcome: the
            # point of the call is that the warning was emitted on the way.
        end
    end
end

\"\"\"
Every shim in scripts/renames.jl, as `old => new`.
\"\"\"
const SHIMS = [
""",
    )
    for (old, new) in RENAMES
        (ismacro(old) || old in TYPE_RENAMES) && continue
        println(io, "    :$old => :$new,")
    end
    print(
        io,
        """
]

@testset "deprecations" begin
    @testset "every shim exists, warns and forwards" begin
        for (old, new) in SHIMS
            @test isdefined(PETSc, old)
            @test isdefined(PETSc, new) || isdefined(Base, new)
            probe_shim(old)
        end
    end

    @testset "renamed types are aliases" begin
""",
    )
    for (old, new) in RENAMES
        old in TYPE_RENAMES || continue
        println(io, "        @test PETSc.$old === PETSc.$new")
    end
    print(
        io,
        """
    end

    @testset "renamed macros warn and forward" begin
""",
    )
    for (old, new) in RENAMES
        ismacro(old) || continue
        call = if old in (Symbol("@petsc_simple_fn"),)
            "PETSc.$old(probe_simple)"
        else
            "PETSc.$old(probe_point, Nf)"
        end
        println(
            io,
            "        warns() do\n" *
            "            macroexpand(DeprecationMacroEnv, :($call))\n" *
            "        end",
        )
    end
    print(
        io,
        """
    end

    @testset "a shim really does forward" begin
        petsclib = PETSc.petsclibs[1]
        PETSc.initialize(petsclib)
        v = PETSc.VecSeq(petsclib, 5)
        # `destroy` is the busiest shim in the rename; check it actually destroys.
        warns() do
            PETSc.destroy(v)
        end
        @test v.ptr == C_NULL
        @test (warns() do
            PETSc.initialized(petsclib)
        end) == PETSc.isinitialized(petsclib)
    end
end
""",
    )
    write(path, String(take!(io)))
    return nothing
end

# ---------------------------------------------------------------------------

check_register()
write_deprecations(joinpath(ROOT, "src", "deprecations.jl"))
write_public(joinpath(ROOT, "src", "public_names.jl"))
write_audit_names(joinpath(ROOT, "src", "audit_names.jl"))
write_tests(joinpath(ROOT, "test", "test_deprecations.jl"))
println("wrote src/deprecations.jl, src/public_names.jl, src/audit_names.jl, test/test_deprecations.jl")
