# This file is generated by scripts/generate_renames.jl from scripts/renames.jl.
# Do not edit it: edit the register and regenerate.
#
# The names src/audit.jl matches against. Generated so that the next rename
# cannot blind the auditor: after a rename its patterns would otherwise stop
# matching and it would report no leaks on leaking code.

"""
    AUDIT_TYPE_CREATORS

Type constructors whose name is also the kind of object they create.
"""
const AUDIT_TYPE_CREATORS = Dict{Symbol, String}(
    :DMDA => "DM",
    :DMPlex => "DM",
    :DMStag => "DM",
    :KSP => "KSP",
    :SNES => "SNES",
)

"""
    AUDIT_NAMED_CREATORS

Creators whose name carries no `Create`/`Duplicate` marker for
[`audit_creator`](@ref) to recognise by shape.
"""
const AUDIT_NAMED_CREATORS = Dict{Symbol, String}(
    :DMCreateMatrix => "Mat",
    :DMGetCoordinateDM => "DM",
    :DMGlobalVec => "Vec",
    :DMLocalVec => "Vec",
    :DMStagCreateCompatibleDMStag => "DM",
    :MatAIJ => "Mat",
    :MatCreateVecs => "Vec",
    :MatSeqAIJ => "Mat",
    :MatSeqDense => "Mat",
    :MatShell => "Mat",
    :VecSeq => "Vec",
    :clone => "DM",
    :dm_create_global_vec => "Vec",
    :dm_create_local_vec => "Vec",
    :dmclone => "DM",
    :global_vec => "Vec",
    :local_vec => "Vec",
)

"""
    AUDIT_DESTROYER_NAMES

Names that release a PETSc object. `finalizer` counts: it hands the release to
the garbage collector rather than performing it, but the object is accounted for.
"""
const AUDIT_DESTROYER_NAMES = Set{Symbol}([:destroy!, :destroy, :finalizer])
