# This file is generated by scripts/generate_renames.jl from scripts/renames.jl.
# Do not edit it: edit the register and regenerate.
#
# Deprecation shims for the v0.5 rename (docs/src/man/naming.md §17). They are
# removed in v0.6.
#
# `Base.@deprecate` is not used: it calls `Base.depwarn`, which prints nothing
# unless Julia was started with `--depwarn=yes`, and a migration window that
# prints nothing is not a migration window (§17.1).

"""
    @renamed old new

Define `old` as a deprecated spelling of `new`.

The generated method forwards every argument and keyword argument, and warns once
per call site. The warning goes through `@warn` rather than `Base.depwarn`, so it
is printed whatever `--depwarn` is set to.
"""
macro renamed(old, new)
    msg = "$old is deprecated, use $new"
    return quote
        function $(esc(old))(args...; kwargs...)
            @warn $msg maxlog = 1
            return $(esc(new))(args...; kwargs...)
        end
    end
end

# Renamed functions

@renamed destroy destroy!
@renamed getinfo info
@renamed getcorners corners
@renamed getcorners_dmda corners
@renamed getghostcorners ghost_corners
@renamed getghostcorners_dmda ghost_corners
@renamed dm_local_to_global! local_to_global!
@renamed dm_global_to_local! global_to_local!
@renamed setuniformcoordinates_dmda! set_uniform_coordinates!
@renamed coordinatesDMLocalVec local_coordinates
@renamed getlocalcoordinatearray local_coordinate_array
@renamed DMGlobalVec global_vec
@renamed DMLocalVec local_vec
@renamed getdimension ndims
@renamed setfromoptions! set_from_options!
@renamed getcorners_dmstag corners
@renamed getghostcorners_dmstag ghost_corners
@renamed local_indices_dmstag local_indices
@renamed global_indices_dmstag global_indices
@renamed setuniformcoordinates_stag! set_uniform_coordinates!
@renamed DMStagDOF_Slot dof_slot
@renamed reshapelocalarray reshape_local_array
@renamed localinteriorlinearindex local_interior_linear_index
@renamed dmda_star_fd_coloring star_fd_coloring
@renamed isplexsimplex issimplex
@renamed plexdistribute! distribute!
@renamed petsc_setname! set_name!
@renamed getds ds
@renamed createds! create_ds!
@renamed getlabel label
@renamed dm_project_function! project_function!
@renamed dm_project_field! project_field!
@renamed dm_compute_l2diff l2diff
@renamed dm_create_global_vec global_vec
@renamed dm_create_local_vec local_vec
@renamed dm_set_auxiliary_vec! set_auxiliary_vec!
@renamed dm_coarsen_hook_add! add_coarsen_hook!
@renamed dm_copy_disc! copy_disc!
@renamed dm_get_coarse coarse_dm
@renamed fe_copy_quadrature! copy_quadrature!
@renamed mat_null_space_create mat_nullspace_create
@renamed mat_set_null_space! set_nullspace!
@renamed mat_null_space_destroy! destroy!
@renamed vtk_save! save_vtk!
@renamed vtk_save_fields! save_vtk!
@renamed setfield! set_field!
@renamed dmclone clone
@renamed plex_set_snes_local_fem! set_snes_local_fem!
@renamed snes_set_jacobian_null_space! set_jacobian_nullspace!
@renamed fe_compose_constant_null_space! compose_constant_nullspace!
@renamed getDM dm
@renamed setDM! set_dm!
@renamed get_solution solution
@renamed gettype type_name
@renamed type type_name
@renamed setcomputeoperators! set_compute_operators!
@renamed setcomputerhs! set_compute_rhs!
@renamed setfunction! set_function!
@renamed setjacobian! set_snes_jacobian!
@renamed setconvergencetest! set_convergence_test!
@renamed VecSeq PetscVec
@renamed MatSeqAIJ PetscMat
@renamed MatSeqDense PetscMat
@renamed MatCreateSeqAIJ PetscMat
function MatSeqAIJWithArrays(args...; kwargs...)
    @warn "MatSeqAIJWithArrays is deprecated, use PetscMat" maxlog = 1
    return mat_seqaij_with_arrays(args...; kwargs...)
end

@renamed MatAIJ PetscMat
@renamed unsafe_localarray unsafe_local_array
@renamed wrap_localarray wrap_local_array
@renamed acquire_petsc_local_array acquire_local_array
@renamed release_petsc_local_array release_local_array
@renamed get_petsc_arrays local_arrays
@renamed restore_petsc_arrays restore_local_arrays!
@renamed withlocalarray! with_local_array!
@renamed ghostupdate! ghost_update!
@renamed ghostupdatebegin! ghost_update_begin!
@renamed ghostupdateend! ghost_update_end!
@renamed ownershiprange ownership_range
@renamed setvalues! set_values!
@renamed addindex! add_index!
@renamed determine_memtype memtype
@renamed Options PetscOptions
@renamed set_petsclib PetscLibType
@renamed initialized isinitialized
@renamed finalized isfinalized
@renamed check_petsc_wrappers_version check_wrappers_version
@renamed getcomm comm
@renamed typedget parse_option
@renamed audit_petsc_file audit_file

# Renamed macros

macro petsc_residual_fn(args...)
    @warn "@petsc_residual_fn is deprecated, use @residual_fn" maxlog = 1
    return Expr(:macrocall, GlobalRef(@__MODULE__, Symbol("@residual_fn")), __source__, args...)
end

macro petsc_jacobian_fn(args...)
    @warn "@petsc_jacobian_fn is deprecated, use @jacobian_fn" maxlog = 1
    return Expr(:macrocall, GlobalRef(@__MODULE__, Symbol("@jacobian_fn")), __source__, args...)
end

macro petsc_bd_fn(args...)
    @warn "@petsc_bd_fn is deprecated, use @bd_fn" maxlog = 1
    return Expr(:macrocall, GlobalRef(@__MODULE__, Symbol("@bd_fn")), __source__, args...)
end

macro petsc_simple_fn(args...)
    @warn "@petsc_simple_fn is deprecated, use @simple_fn" maxlog = 1
    return Expr(:macrocall, GlobalRef(@__MODULE__, Symbol("@simple_fn")), __source__, args...)
end


# Renamed types: a `const` alias, so `isa` and dispatch keep working

const Fn_KSPComputeRHS = KSPComputeRHSFn
const Fn_KSPComputeOperators = KSPComputeOperatorsFn
const Fn_SNESSetFunction = SNESSetFunctionFn
const Fn_SNESSetJacobian = SNESSetJacobianFn
const Fn_SNESSetConvergenceTest = SNESSetConvergenceTestFn
# `AbstractPETScMemBackend` is aliased where `AbstractPetscMemBackend` is defined.
