# This file is generated by scripts/generate_renames.jl from scripts/renames.jl.
# Do not edit it: edit the register and regenerate.
#
# The high-level API that is not exported (docs/src/man/naming.md §13.1).
# Julia 1.12 is the minimum supported version, so this is unconditional.

public @bd_fn, @jacobian_fn, @residual_fn, @simple_fn, AbstractPetscDS,
       AbstractPetscMemBackend, KSPComputeOperatorsFn, KSPComputeRHSFn, MatOp, MatPtr,
       MatShell, PetscDS, PetscLibType, PetscNotInitialized, SNESSetConvergenceTestFn,
       SNESSetFunctionFn, SNESSetJacobianFn, TSMonitorSetFn, TSSetIFunctionFn,
       TSSetIJacobianFn, TSSetRHSFunctionFn, TSSetRHSJacobianFn, VecPtr,
       acquire_local_array, add_boundary!, add_coarsen_hook!, add_index!,
       add_natural_boundary!, array_type, assemble!, audit_file, check_wrappers_version,
       clone, coarse_dm, comm, compose_constant_nullspace!, converged_reason, copy_disc!,
       copy_quadrature!, corners, create_ds!, create_split_boundary_labels!, current_time,
       destroy!, distribute!, dm, dof_slot, ds, fe_create_default, fe_create_lagrange,
       finalize, ghost_corners, ghost_update!, ghost_update_begin!, ghost_update_end!,
       global_indices, global_to_local!, global_vec, info, initialize, interpolate!,
       inttype, isfinalized, isinitialized, issimplex, ksp, ksp_iterations, l2diff, label,
       library_info, local_arrays, local_coordinate_array, local_coordinates, local_indices,
       local_interior_linear_index, local_to_global!, local_vec, mat_nullspace_create,
       max_steps, max_time, memtype, memtype_backend, narrow, ndofs, ownership_range, owns,
       parse_option, parse_options, project_field!, project_function!, release_local_array,
       reset!, reshape_local_array, restore_local_arrays!, save_vtk!, scalartype,
       set_adapt_type!, set_auxiliary_vec!, set_compute_operators!, set_compute_rhs!,
       set_constants!, set_convergence_test!, set_dm!, set_exact_final_time!,
       set_exact_solution!, set_field!, set_from_options!, set_function!, set_ifunction!,
       set_ijacobian!, set_jacobian!, set_jacobian_nullspace!, set_jacobian_preconditioner!,
       set_library!, set_max_steps!, set_max_time!, set_monitor!, set_name!, set_nullspace!,
       set_problem_type!, set_residual!, set_rhs_function!, set_rhs_jacobian!,
       set_snes_jacobian!, set_snes_local_fem!, set_solution!, set_time!, set_timestep!,
       set_tolerances!, set_type!, set_uniform_coordinates!, set_user_ctx!, set_values!,
       setup!, snes, snes_failures, snes_iterations, solution, solve!, solve_time,
       star_fd_coloring, step!, step_number, step_rejections, tao_usable_after_reinitialize,
       timestep, tolerances, type_name, unsafe_local_array, unset_library!, user_ctx,
       vtk_merge_tensor!, with_local_array!, wrap_local_array
